### ISSUE TITLE
nested lists is not displayed in query results table

### ISSUE THREAD

**Issue by uchti** [ElasticHQ/elasticsearch-HQ#108]
Nested lists is not displayed in query results table.

for example my mappings 
{
  "mappings": {
    "test": {
      "_source": {
        "enabled": false
      },
      "properties": {
        "data": {
          "properties": {
            "w": {
              "type": "integer",
              "store": "yes"
            },
            "name": {
              "type": "string",
              "store": "yes"
            }
          }
        }
      }
    }
  }
}

**Comment by bogdanovich** [comment]
Got the same issue :(

**Comment by HarveyWilliams** [comment]
This still seems to be a problem.
