### ISSUE TITLE
Query page fields selected does not reflect indices

### ISSUE THREAD

**Issue by krone** [ElasticHQ/elasticsearch-HQ#115]
Fields selected/available should reflect that of indices selected. Currently all fields are shown/selected even if the respective indices are not.

Hope that makes sense.
![red](https://f.cloud.github.com/assets/519497/1812925/d8a73be8-6e99-11e3-937f-4e1c5c2f2567.png)

**Comment by mcheptea** [comment]
@krone I realize this is an old issue, but you can have a look at my PR and let me know of this solves your problem.
