### ISSUE TITLE
Add Node picker on Diagnostics screen

### ISSUE THREAD

**Issue by royrusso** [ElasticHQ/elasticsearch-HQ#121]
Over 20 nodes, causes browser to stall... either affected from network latency, ajax timeout, or memory on the client. Adding a node selection box when > 10 nodes detected can help. Additionally, filtering by node-name would work: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/cluster.html

curl localhost:9200/_cluster/nodes/node_name_goes_*

Topic: https://groups.google.com/forum/?fromgroups=#!topic/elastichq/iQnsY4ScUag

**Comment by Rylon** [comment]
Hi @royrusso I have a question about this feature - is it possible to pre-set this filter, via URL parameters or something similar, so that I could link directly to the node diagnostics, with only the data nodes filtered for display?
