### ISSUE TITLE
Accessing elastic hq when port 9200 is blocked with apache proxy

### ISSUE THREAD

**Issue by jerrac** [ElasticHQ/elasticsearch-HQ#143]
For security reasons, I have port 9200 blocked outside the subnet my nodes live in. With Kibana, I was able to get it working by using apache to proxy it. 

Like this:

```
<Proxy http://node.domain.tld:9200>
  ProxySet connectiontimeout=5 timeout=90
</Proxy>

<LocationMatch "^/(_nodes|_aliases|_search|.*/_search|_mapping|.*/_mapping)$">
  ProxyPassMatch http://node.domain.tld:9200/$1
  ProxyPassReverse http://node.domain.tld:9200/$1
</LocationMatch>

<LocationMatch "^/(kibana-int/dashboard/|kibana-int/temp)(.*)$">
  ProxyPassMatch http://node.domain.tld:9200/$1$2
  ProxyPassReverse http://node.domain.tld:9200/$1$2
</LocationMatch>
```

If I change 

```
<LocationMatch "^/(kibana-int/dashboard/|kibana-int/temp)(.*)$">
```

to:

```
<LocationMatch "^/(kibana-int/dashboard/|kibana-int/temp|_plugin)(.*)$">
```

I can load the initial ElasticHQ connect page. But when I put node.domain.tld into the connect box and click connect, it says it can't connect. Likewise if I add :9200 to the url.

So, I assume I've missed something in how apache proxies things. Any suggestions?

**Comment by dfaropennetwork** [comment]
Thx so much, it's a very useful info
