### ISSUE TITLE
"Unable to Connect to Server! Received Status Code: 200."

### ISSUE THREAD

**Issue by ddossot** [ElasticHQ/elasticsearch-HQ#148]
We're running the ElasticSearch API behind Nginx (port 80 -> 9200). Kibana works fine with this setting.

We've deployed HQ and we're getting this puzzling error message:

`"Unable to Connect to Server! Received Status Code: 200."`

The browser console shows successful (HTTP 200) calls made by HQ to `/_cluster/health` and `/_cluster/state` and no failed HTTP requests, so we don't understand why the plug-in refuses to work.

Thank for any help with this.

**Comment by PhilippWoe** [comment]
Same problem here..

**Comment by PhilippWoe** [comment]
I just figured out a solution. You have to start your browser without web security.

http://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

**Comment by ddossot** [comment]
Oh great finding :+1: It's a CORS issue then... which is not obvious at all from the message.

It still needs fixing though, your workaround is nice for testing but not a real solution.

**Comment by PhilippWoe** [comment]
You can also set a flag in config/elasticsearch.yaml to allow CORS. But I preferred the pragmatic way, as I am just debugging ;)

**Comment by KlavsKlavsen** [comment]
I get the exact same error message.. in NET column in firebug in firefox I see it connects to _state _cluster/health etc.. and every request sends get a 200 (and I tried calling them manually - they return fine json).. so I can't figure out whats wrong. Any help as how to debug would be helpful.

**Comment by KlavsKlavsen** [comment]
and it keeps sending the _status and _cluster/.. requests at regular interval.. so it seems to be "somewhere" it simply decides "its not up" - even though everything works.

Only details I can think of - is that going to / - does NOT return the usual elasticsearch json response (version and "you know for search" -msg). kibana reponds there - and works fine.

**Comment by royrusso** [comment]
What version of elasticsearch are you using? Did you install hq as a plugin or is it making a cross domain request?

**Comment by KlavsKlavsen** [comment]
sorry for being lacks in details. I installed it under my kibana vhost.. which proxypass'es to es below.
Using elasticsearch 1.7.1. I tried running it in chromium-browser - started with the "web security" disable options - with no luck.

**Comment by PhilippWoe** [comment]
It's a CORS problem, as ddossot said. You can enable the CORS in the elasticsearch config https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html or disable the CORS check in your browser ;)

**Comment by KlavsKlavsen** [comment]
@PhilippWoe if this is the case - then why does running: chromium-browser --disable-web-security - not resolve the issue?

I'm guessing it "checks for something that isn't true.. is there a .js file I can add a breakpoint to - to try and debug?

**Comment by KlavsKlavsen** [comment]
"checks for something that isn't true": since all requests seems fine and there's nothing in the javascript console - except for access to http://www.elastichq.org/api/hq_settings.php?uuid=db99ac41-88db-c802-7cea-726e00825f2a&_=1449484268046 denied (because I'm on https) - elastichq seems to want to phone home?

**Comment by PhilippWoe** [comment]
@KlavsKlavsen ah sry did not notice that.. that's weird indeed
