### ISSUE TITLE
Query UI, display Search button on top of fields

### ISSUE THREAD

**Issue by dimzak** [ElasticHQ/elasticsearch-HQ#157]
Hi,

My main problem is when I have an index with many fields. Around 70 right now, so for a search query I have to scroll down to "search" every time. I imagine others may have encountered this problem, especially now that all fields from different indexes show in the UI (issue #115)

**Comment by ximex** [comment]
:+1:

**Comment by mcheptea** [comment]
@dimzak you can toggle the fields and hide them. Additionally I created a PR which show only the fields for the selected indices/types.
