### ISSUE TITLE
Feature Request: Create Mapping

### ISSUE THREAD

**Issue by ghost** [ElasticHQ/elasticsearch-HQ#168]
A nice feature would be to create a mapping using the elasticsearch api
http://www.elasticsearch.org/guide/en/elasticsearch/reference/1.x/indices-put-mapping.html

**Comment by hellboy81** [comment]
Vote +1 !

**Comment by muthu1086** [comment]
+1

**Comment by Blakko** [comment]
+1

**Comment by huksley** [comment]
+1

**Comment by hellboy81** [comment]
Please provide the [correct  URL](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html)
