### ISSUE TITLE
ES 1.4.x not able to connect

### ISSUE THREAD

**Issue by alex-leonhardt** [ElasticHQ/elasticsearch-HQ#173]
Hi,

I've been trying ES 1.4 Beta and it seems there are some incompatibilities now. This works great with 1.3.x - but is unable to get "the data" or connect (??) to ES instances running 1.4.x.

Let me know if you need some more details ?

Alex

**Comment by chorsley** [comment]
Am running ES 1.4.2, and both connection via HQ and ```/_cluster/health``` appear to work for me.

**Comment by odin88** [comment]
Using Elasticsearch 1.5.2 and I still need to follow @gmcneel guide to be able to use it. :(

**Comment by jinou624** [comment]
I'm using 1.5.2 on Linux,but it's always can not connect success after I add "http.cors.enabled: true" in elasticsearch.yml,with restart elasticsearch service
