### ISSUE TITLE
Uncaught TypeError: Cannot read property 'num_docs' of undefined

### ISSUE THREAD

**Issue by darkpixel** [ElasticHQ/elasticsearch-HQ#179]
The error:

```
ncaught TypeError: Cannot read property 'num_docs' of undefined
```

appears in the javascript console and I am unable to click on an index.  It appears to be only indexes that are currently syncing with new nodes.

I was unable to click on logstash-2014.12.17 a few minutes ago.  After it finished syncing (and started syncing 2014.12.16) I was able to click on it, but not 2014.12.16.

**Comment by dezsenyi** [comment]
I have the same problem, but the indices are not syncing.
I modified the mappings of the indices. Before the modification, HQ worked well, but with the new mappings I have the following JS errors:

**Error message when I click to "Indices"**
```
Uncaught TypeError: Cannot read property 'primary_size_in_bytes' of undefined
(anonymous function) @ VM192:18w.each.w.forEach @ underscore-min.js:1(anonymous function) @ VM192:10c @ underscore-min.js:1Backbone.View.extend.render @ all.min.js:13(anonymous function) @ all.min.js:14c @ jquery.1.9.1.min.js:3p.fireWith @ jquery.1.9.1.min.js:3k @ jquery.1.9.1.min.js:5r @ jquery.1.9.1.min.js:5
```
**Error message when I click to a particular index**
```
Uncaught TypeError: Cannot read property 'num_docs' of undefined
(anonymous function) @ VM156:18c @ underscore-min.js:1Backbone.View.extend.render @ all.min.js:13(anonymous function) @ all.min.js:14c @ jquery.1.9.1.min.js:3p.fireWith @ jquery.1.9.1.min.js:3(anonymous function) @ jquery.1.9.1.min.js:3c @ jquery.1.9.1.min.js:3p.fireWith @ jquery.1.9.1.min.js:3k @ jquery.1.9.1.min.js:5r @ jquery.1.9.1.min.js:5
```

Unfortunately I modified a bunch of things (complete mapping refactoring), so I cannot determine what could cause the problem...
ElasticSearch version: 1.4.5

**Comment by krzyszt0fd** [comment]
Hi, I 
had same issue and it turned out i installed wrong HQ verions for my elastic instance.
Please refer to https://github.com/royrusso/elasticsearch-HQ#version-compatibility
