### ISSUE TITLE
Allow PUT, DELETE request in REST Editor

### ISSUE THREAD

**Issue by blured75** [ElasticHQ/elasticsearch-HQ#199]
Hello,

The REST Editor does not allow PUT request neither DELETE. Could you add that ?

Regards,
Denis.

**Comment by jalaziz** [comment]
@royrusso Was this closed because it won't be fixed? I can't find the functionality in ElasticHQ unless I'm missing something?

**Comment by royrusso** [comment]
I will reopen. Probably closed it in error as part of the rebuild.
