### ISSUE TITLE
Cluster State Problem

### ISSUE THREAD

**Issue by felipegs** [ElasticHQ/elasticsearch-HQ#206]
http://localhost:9200/_cluster/state?filter_nodes=false&filter_metadata=true&filter_routing_table=true&filter_blocks=true&filter_indices=true

This call on the browser return an empty payload.
If a run that on node it return a really really big payload. Probably it will crash the brower if the response was not empty

Elasticsearch 1.7.2

**Comment by royrusso** [comment]
How is this an HQ issue?

**Comment by felipegs** [comment]
This return a very big payload more than 30MB, I stoped the request when it achieve this value and it does this request more than once. And the browser crashs

**Comment by felipegs** [comment]
Filters are wrong
https://www.elastic.co/guide/en/elasticsearch/reference/1.7/cluster-state.html#_response_filters

**Comment by royrusso** [comment]
Wrong?... as in that they aren't being used?
