### ISSUE TITLE
Issues connecting to protected elasticsearch instance

### ISSUE THREAD

**Issue by dani190** [ElasticHQ/elasticsearch-HQ#209]
Hey guys,

When trying to connect to my elasticsearch instance that is secured with http.basic.user and http.basic.password i cannot connect to it using elasticsearch-HQ.

The error I get is as follows:

Error!
Unable to Connect to Server! Received Status Code: 0. A status code of 0, could mean the host is unreacheable or nothing is listening on the given port.

Does elasticsearch-HQ have the ability to define the username and password to login?

**Comment by royrusso** [comment]
Did you try: http://USERNAME:PASSWORD@DOMAIN:9200   ?

**Comment by dani190** [comment]
Yes and that's when I get that unable to connect to server! Received status code 0.

**Comment by royrusso** [comment]
I'm assuming you've enabled CORS and that's not the issue?

**Comment by dani190** [comment]
It's actually just the standard http username defined in the elasticsearch.yml file.

**Comment by royrusso** [comment]
? Are you using the security plugin? I don't understand how you have a username in your ES config.

**Comment by dani190** [comment]
I have http.basic.user defined

It's the elasticsearch-http-basic project by Asquera.

**Comment by royrusso** [comment]
What happens when you go to your browser and hit: http://USERNAME:PASSWORD@DOMAIN:9200 ?

Also, are you running HQ installed or from where?

**Comment by dani190** [comment]
I get OK.

I installed it on a Linux box on the same network.
