### ISSUE TITLE
CPU and DIsk IOPs stats not displayed

### ISSUE THREAD

**Issue by ajaybhatnagar** [ElasticHQ/elasticsearch-HQ#225]
With new ES version, stats are not captured/displayed correctly.
HQ version 2.0.3, ES version 2.0.0. Running in KVM setup  with OS Ubuntu 3.16.0-52.

Operating System

Uptime: NaN:NaN:NaN
Total Memory:   15.67 GB
Total Swap: 0 B
Memory (Used/Free): 12.56 GB / 3.11 GB
Swap (Used/Free):   0 B / 0 B
CPU User/Sys:   % / %
CPU Idle:   %
CPU Vendor: N/A
CPU Model:  N/A
# Total Cores:    N/A

(Disk IOPS when inserting documents in bulk simultaneously by multiple connection)

FileSystem 0 

Path:   /es1/data/elasticsearch/es-test-chef/nodes/0
Mount:  /es1 (/dev/sda)
Device: 
Total Space:    98.3GB
Free Space: 95.0GB
Disk Reads: 0
Disk Writes:    0
Read Size:  0.0
Write Size: 0.0

**Comment by zakswindow** [comment]
I am having same issue too. Any solutions guys?

**Comment by apetrovYa** [comment]
:+1:

**Comment by oneiros-de** [comment]
@royrusso Since you closed it without any comment: Is this now a feature?

**Comment by royrusso** [comment]
I will reopen it, in case someone wants to take it on as an issue, but with v3 coming, I don't plan on spending any time fixing the older versions. v3 will support this across all ES versions.
