### ISSUE TITLE
Wrong info about #doc

### ISSUE THREAD

**Issue by naivefun** [ElasticHQ/elasticsearch-HQ#226]
I get result from /_count:
{
   "count": 4723181,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   }
}

but in HQ it says I have 35,968,288 #Doc for this index.

https://www.dropbox.com/s/yve0zqwwhz924b2/Screenshot%202015-11-18%2006.59.33.png?dl=0

**Comment by thalesfsp** [comment]
@naivefun @royrusso 1 month later and some information about why this is happening?

**Comment by naivefun** [comment]
@thalesfsp  I have no idea. the #Doc seems never the actual count of an index, it's also not count * no of replica. I didn't read the source code to find out how this is calculated, I guess it is not the count of an index in the first place.

**Comment by thalesfsp** [comment]
Got it, tkx!
