### ISSUE TITLE
unable to open index (_status API replaced in 2.x)

### ISSUE THREAD

**Issue by blanche** [ElasticHQ/elasticsearch-HQ#229]
trying to open an index from the overview page, i get an 400 bad request error because the _status API has been replaced with the Indices Stats API

https://www.elastic.co/guide/en/elasticsearch/reference/2.x/indices-status.html

this makes it impossible to view stats or delete an index

**Comment by entropyfarms** [comment]
Any resolution on this issue?  I really like the look-feel of elasticsearchHQ but this is a pretty hard showstopper against any new ES installation.  Can anybody with knowledge of the new indicies endpoints comment whether this requires a complete overhaul or just a few minor url updates within ES-HQ?

**Comment by royrusso** [comment]
Are you using the plugin install version? For 2.x, do not use the version that's live on elastichq.org.
