### ISSUE TITLE
No reaction when typing http://ip:port

### ISSUE THREAD

**Issue by tottishi05** [ElasticHQ/elasticsearch-HQ#230]
I deploy a ElasticSearch `1.5.2` cluster on Cent OS `6.4`
I install ElasticHQ `1.0` by uploading the zip package on each ElasticSearch server of my cluster.
I install the plugin using the options below:
`plugin -i HQ -u file://zipfilelocation`
When I access the plugin, type the url and click the `Connect` it has no reaction as below:
![elastichq](https://cloud.githubusercontent.com/assets/11494098/12220758/80404150-b7b9-11e5-9551-b791499e4f4c.png)
The `loading` sign on the right of the `Connect` button keeps rotating.

**Comment by zeroly** [comment]
修改浏览器编码为utf-8 或者自动

**Comment by qianglchina** [comment]
i have the same problem, and it works !!

**Comment by felayman** [comment]
I have the same problem, and it works !!!
