### ISSUE TITLE
Is elasticsearch-HQ supporting  ES version 2.1.1 ?

### ISSUE THREAD

**Issue by srinvas** [ElasticHQ/elasticsearch-HQ#235]

**Comment by royrusso** [comment]
Needs testing.

**Comment by limdauto** [comment]
I have no trouble using it with 2.1.1

**Comment by La5DotNet** [comment]
I user es 2.1.1,it can't work!

Uncaught SyntaxError: missing ) after argument list
all.min.js:15 Uncaught TypeError: Cannot read property 'addParser' of undefined
elastichq.js:40 Uncaught TypeError: doFocus is not a function
