### ISSUE TITLE
HQ can not access ES with http auth

### ISSUE THREAD

**Issue by henghenghahai** [ElasticHQ/elasticsearch-HQ#246]
Hi Sir,
my elasticsearch is 2.3.0,which enabled http auth(enter an account/password when access http://localhost:9200), after I installed elasticsearch-HQ plugin, it failed to access elasticsearch when type http://localhost:9200.

Error!
Unable to Connect to Server! Received Status Code: 0. A status code of 0, could mean the host is unreacheable or nothing is listening on the given port. Did you enable CORS? 

my elasticsearch.yml has enabled the following item:
http.cors.enabled: true
http.cors.allow-origin: "*"

how can  HQ could access elasticsearch when enabled http auth?
thank you.

**Comment by MTRNord** [comment]
Same error here

**Comment by Nayar** [comment]
Same here

**Comment by sshantveer** [comment]
Same issue. Unable to connect to elastic 2.2.0 version.
