### ISSUE TITLE
Change opt-out to opt-in for stats collection

### ISSUE THREAD

**Issue by mdamien** [ElasticHQ/elasticsearch-HQ#247]
The user should be giving the choice to opt-in when he first access the app. Making the setting hidden in the settings and true my default is, in my opinion, a bad thing. What do you think ?

**Comment by aleho** [comment]
This is especially true as statistics and version check are unencrypted and will be blocked by the browser anyway if EHQ is served via HTTPS.

From a security point of view its crucial EHQ API switched to HTTPS (e.g. by using lets encrypt).
