### ISSUE TITLE
Node Information Broken

### ISSUE THREAD

**Issue by mllewellyn** [ElasticHQ/elasticsearch-HQ#250]
When I try to view the node diagnostics page nothing happen on the screen and an "Uncaught TypeError: Cannot read property 'vendor' of undefined all.min.js:13" The error is thrown on line 13, column 17906 of all.min.js.

This may be related to issue #251.

**Comment by dpratt** [comment]
It's been over two months with no comment. This bug utterly breaks pretty much any non-trivial usage of elastichq. Is there any plan at all to address this, or is this project dead?

If so, is there a fork somewhere?

**Comment by XerMajor** [comment]
@dpratt Hi David. Do you know how to fix this problem?

**Comment by XerMajor** [comment]
@dpratt @mllewellyn it works if you run it from sources
