### ISSUE TITLE
Node Diagnostics Broken

### ISSUE THREAD

**Issue by mllewellyn** [ElasticHQ/elasticsearch-HQ#251]
When I try to view the node diagnostics page nothing happen on the screen and an "Uncaught TypeError: Cannot read property 'evictions' of undefined all.min.js:13" The error is thrown on line 13, column 12095 of all.min.js.

This may be related to issue #250.

**Comment by XerMajor** [comment]
Does someone know how to fix this issue?

**Comment by XerMajor** [comment]
@mllewellyn it works if you run it from sources

**Comment by bluebob** [comment]
Which version are you running? I've got a couple of v2.0.3 installs here and none of them are showing the error you're getting, so I'm wondering if that's the "run it from sources" version that XerMajor is talking about.

**Comment by XerMajor** [comment]
@bluebob I think the issue is about http://www.elastichq.org
