### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by weiboyiyou** [ElasticHQ/elasticsearch-HQ#253]
jquery.tablesorter.min.js:4 Uncaught SyntaxError: missing ) after argument list
all.min.js:15 Uncaught TypeError: Cannot read property 'addParser' of undefined
elastichq.js:40 Uncaught TypeError: doFocus is not a function
http://192.168.163.162:9200/favicon.ico Failed to load resource: the server responded with a status of 400 (Bad Request)
all.min.js:12 http://192.168.163.162:9200/
ModelUtil.js:47 Could not parse URL for auth credentials! tokenizeUserPassFromURL is not a function
all.min.js:12 Inside ClusterHealth
all.min.js:12 Inside ClusterState
all.min.js:12 Inside IndexStatsModel
all.min.js:12 Inside NodeList
ModelUtil.js:47 Could not parse URL for auth credentials! tokenizeUserPassFromURL is not a function
all.min.js:12 Successful connect!

**Comment by laoshancun** [comment]
i have same problem too,did you solve it?

**Comment by KurtRao** [comment]
me too, with the same problem, on all branches and tags.

**Comment by KurtRao** [comment]
got it. see #192
