### ISSUE TITLE
Query page returns no results when search field includes an object or nested type

### ISSUE THREAD

**Issue by scotttam** [ElasticHQ/elasticsearch-HQ#254]
Fields that are _object_ or _nested_ types cannot specify [fields](https://www.elastic.co/blog/found-managing-elasticsearch-fields-when-searching) for a _search. So for example, if specifying the search below and assuming geo is either an object or nested type:

`
curl -XPOST http://localhost:9200/media/_search -d '{
  "from": 0,
  "size": 50,
  "sort": {
    "_score": {
      "order": "asc"
    }
  },
  "fields": [
    "geo"
  ],
  "explain": true
}' 
`
the following error will result:

`
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"field [geo] isn't a leaf field"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query_fetch","grouped":true,"failed_shards":[{"shard":0,"index":"media","node":"cHgeASLfQgCFAMhejmNrBQ","reason":{"type":"illegal_argument_exception","reason":"field [geo] isn't a leaf field"}}]},"status":400}
`
This isn't obvious from the http://localhost:9200/_plugin/hq/#documents page. When selecting one of these types of fields, nothing happens when hitting the search button. I might suggest either graying out these fields or having some sort of indication that there was an error.

**Comment by efowler** [comment]
+1  It sure would be nice to be able to see the nested objects in the search results (even if it can't be searched directly)
