### ISSUE TITLE
Refreshing the browser tab returns to the index page

### ISSUE THREAD

**Issue by jean-lourenco** [ElasticHQ/elasticsearch-HQ#257]
Sorry if this is a stupid question, but why does F5 have this behavior?

Everytime I get myself forgeting the fact that I can't refresh the page, and so I have to reconnect again to the ElasticSearch.

It's just annoying, but something that could be fixed easily i guess.

**Comment by Tattao** [comment]
I think it can change you browser setting with encoding when you after did F5.(PS: sorry ,my english is very terrible~~)
