### ISSUE TITLE
Add an official Docker image

### ISSUE THREAD

**Issue by jamyouss** [ElasticHQ/elasticsearch-HQ#258]
Could be great to have an official Docker image of elasticsearch-HQ !

**Comment by thebennos** [comment]
+1

**Comment by Vic-Wu** [comment]
+1

**Comment by jangrewe** [comment]
+1

**Comment by geraldclark** [comment]
+1

**Comment by royrusso** [comment]
Have you folks looked under the deployment folder. There are docker configs there.

**Comment by jangrewe** [comment]
To clarify this issue: an "official Docker image" would be a Docker image available on https://hub.docker.com

The files in the `deployment` folder may (or may not, didn't try them) help somebody build their own image, but there are already a couple of them out there - none of them actively maintained, though.
Providing an official image is quite easy, just create a Dockerfile in the git repo have the Docker Hub automatically build new images on commits to the git repo.

**Comment by royrusso** [comment]
Makes sense. I reopened this issue, and will look in to adding it in the next release.

Note that the entire HQ codebase changed this week with the new release, so any older version docker images that are out there, won't be supported.

**Comment by royrusso** [comment]
Dockerhub image added and tested with latest master branch: https://hub.docker.com/r/elastichq/elasticsearch-hq/
