### ISSUE TITLE
Cannot manage any closed index

### ISSUE THREAD

**Issue by plrunner** [ElasticHQ/elasticsearch-HQ#259]
Hi,
when I close an index from its own Administration tab, then I get automatically returned back to the list of indexes. There I can no longer enter the details page of that index by clicking on it.

By inspecting with chrome I can see that's due to the fact ES does not return the _stats of a closed index (index_closed_exception). So, from an ES perspective this is the ordinary behaviour (in facts its stats are not available).

Although I am a first-try user and must admit that keeping the index clickable after it gets closed is kind of misleading. A possible solution is making it not clickable or, even better, giving the user only the possibility to reopen it.

Kind Regards, and thanks for this amazing tool
PL

**Comment by hackzilla** [comment]
Would be nice if you could click back into the index to either delete it or reopen it.
