### ISSUE TITLE
Visualize graph breaks and keeps the text trail as it collapses

### ISSUE THREAD

**Issue by sudheesh001** [ElasticHQ/elasticsearch-HQ#261]
Steps to reproduce:
1. Visualize the graph
   ![ehq1](https://cloud.githubusercontent.com/assets/4545925/18382707/cc91e400-769f-11e6-9d54-3f49caa5327c.PNG)
2. Collapse a node
   ![ehq2](https://cloud.githubusercontent.com/assets/4545925/18382718/d19838c8-769f-11e6-98ff-da24ea968697.PNG)

**Comment by bluebob** [comment]
sudheesh001, I didn't know you could collapse nodes, but I just tried that on my local system (OS X El Capitan with Chrome Version 53.0.2785.116 (64-bit)) and it works fine. So I'm thinking that this _might_ be a browser issue. Want to share what configuration you're using?
