### ISSUE TITLE
Nothing shown in Node diagnostics

### ISSUE THREAD

**Issue by bbalakri** [ElasticHQ/elasticsearch-HQ#276]
I see the following exception getting printed repeatedly in the server log.  More over I don't see anything shown for node diagnostics. Any hint would help.

java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'completion090' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene50, IDVersion, completion,
Lucene40, Lucene41]

**Comment by SantoshKumarA** [comment]
I'm also facing similar exception.. Could there be any help on this..

Installed HQ plugin as part of elasticsearch and taken AWS AMI..

When spinning up new AWS instance and starting the Elasticsearch - it takes 8 to 10 mins to start. Seeing the above exception repeatedly..

**Comment by royrusso** [comment]
This isn't an ElasticHQ issue. You're having issues with Elasticsearch.

**Comment by royrusso** [comment]
That exception is being thrown by Elasticsearch. It isn't related to ElasticHQ at all. Try the Elasticsearch github: https://github.com/elastic/elasticsearch
