### ISSUE TITLE
The README.md should be updated

### ISSUE THREAD

**Issue by niravradia** [ElasticHQ/elasticsearch-HQ#285]
See [https://github.com/royrusso/elasticsearch-HQ/issues/282](https://github.com/royrusso/elasticsearch-HQ/issues/282)

I tried to install with royrusso/elasticsearch-HQ but failed with ES v2.4.4. The installation worked with royrusso/elasticsearch-hq/v2.0.3
The README.md still displays a process the old process. Either the installation process is broken or the README.md is outdated.

**Comment by JonathanAquino** [comment]
The full command is given in #282 

Not only the README.md needs to be updated but also the instructions at http://www.elastichq.org/support_plugin.html
