### ISSUE TITLE
HQ does not work with Amazon Elasticsearch

### ISSUE THREAD

**Issue by Ksennios** [ElasticHQ/elasticsearch-HQ#286]
From the javascript console:

Drawing clusterHealth elasticsearch  all.min.js:13:4137
TypeError: this.stateModel.get(...) is undefined[Learn More]  all.min.js:13:3097

With locally installed Elasticsearch 5.4 works without errors

**Comment by royrusso** [comment]
The new HQ v3 in master should work now.
