### ISSUE TITLE
Can't install plugin on ES 5.4

### ISSUE THREAD

**Issue by hrishikeshvganu** [ElasticHQ/elasticsearch-HQ#289]
```
[elasticsearch@c7d826cfc130 ~]$ elasticsearch-plugin install "elasticsearch-HQ/v5.0.0"
A tool for managing installed elasticsearch plugins

Commands
--------
list - Lists installed elasticsearch plugins
install - Install a plugin
remove - removes a plugin from Elasticsearch

Non-option arguments:
command

Option         Description
------         -----------
-h, --help     show help
-s, --silent   show minimal output
-v, --verbose  show verbose output
ERROR: Unknown plugin elasticsearch-HQ/v5.0.0
```

**Comment by TheFireCookie** [comment]
You cannot install site web plugins on ElasticSearch anymore...
Some doc: https://www.elastic.co/guide/en/elasticsearch/plugins/5.4/intro.html

**Comment by pulkitsinghal** [comment]
Hello @TheFireCookie and @hrishikeshvganu 

I was able to get another site plugin going with simple advice from:
https://www.elastic.co/blog/running-site-plugins-with-elasticsearch-5-0

And if you are looking for a more concrete example of a site plugin which adapted to this approach, you can refer to [es-head](https://github.com/mobz/elasticsearch-head#running) plugin.

**Comment by nickel715** [comment]
With ES 5 you have to choose one of the two other options (cloud or local installation).
Also keep in mind that you have to configure cors in your elasticsearch instance to allow elastichq accessing ES with ajax
