### ISSUE TITLE
Documentation on running locally

### ISSUE THREAD

**Issue by jjbursik** [ElasticHQ/elasticsearch-HQ#292]
Does documentation exist on running locally?  I've followed the `npm and grunt` commands that are in the documentation but I don't see anything about spinning up a server and navigating to localhost:9000, etc.

Has anyone done this before?  If so, any help?

**Comment by bluebob** [comment]
npm and grunt? I thought all that was required for the non-plugin was a webserver and a copy of the tarball that you can download from the same place as the plugin?
That said, I'm having zero luck getting it working with my combo of Nginx and ES5.3. :(

**Comment by royrusso** [comment]
https://groups.google.com/forum/#!topic/elastichq/rZOBFNePRKg
