### ISSUE TITLE
ES 5.0

### ISSUE THREAD

**Issue by mattyp999** [ElasticHQ/elasticsearch-HQ#298]
What a shame that you have written such a great piece of software and then seemingly dumped it!

For those trying to get the Querying to work with ES 5.0

1. You'll need to modify the all.min.js file as there appears to be no way to update this easily and it does not pull in the search object from js\model\query\queryutil.js [why not?)

2. Change 

queryObj:{
            "query":{
                "filtered":{
                    "match":{

to

queryObj:{
            "query":{
                "bool":{
                    "must":{

3. do a global change on 'fields' and change to 'stored_fields'

4. Now I got the search working but it won't display field values from the _source - where do I have to go to get this bit working.

Wow! don't we just love hacking thru other people's impenetrable code. I would pay for you to fix this properly? Any takers? Such a shame.

**Comment by smg-mbostwick** [comment]
Did you post a bounty somewhere ? 
http://www.coderbounty.com/list/

**Comment by smg-mbostwick** [comment]
@royrusso hacktober fest label ?

**Comment by mattyp999** [comment]
Are you offering to fix elastichq?


Matthew Pollock
e: mattyp@pollocks.london
m: +44 779988 4020
--- via iPhone ---

**Comment by smg-mbostwick** [comment]
I'd be happy to offer some commits for https://hacktoberfest.digitalocean.com/

**Comment by royrusso** [comment]
https://groups.google.com/forum/#!topic/elastichq/rZOBFNePRKg

**Comment by poorvig89** [comment]
@mattyp999 
In all.min.js. try changing 
queryObj:{query:{filtered:{query:{query_string:{query:""}}}},fields:null,from:0,size:10,sort:[{_score:{order:"asc"}}],explain:!0}} 
to 
queryObj:{query:{bool:{query:{query_string:{query:""}}}},from:0,size:10,sort:[{_score:{order:"asc"}}],_source:null,explain:!0}}

worked for me

**Comment by royrusso** [comment]
This is fixed in the develop_3_0_0 branch. There are no plans to enhance prior releases of HQ.
