### ISSUE TITLE
Cannot read property 'operations' of undefined

### ISSUE THREAD

**Issue by robinWeng0315** [ElasticHQ/elasticsearch-HQ#299]
in ES5.5.3
when i click for node information,i got this error: 
all.min.js:13 Uncaught TypeError: Cannot read property 'operations' of undefined
    at render (all.min.js:13)

the attr of 'operations' from here:
 var m = a.nodes[c].fs.io_stats;
            k.total_in_bytes = a.nodes[c].fs.total.total_in_bytes,
            k.free_in_bytes = a.nodes[c].fs.total.free_in_bytes,
            k.operations = m.total.operations,

**Comment by dvas0004** [comment]
This is because the master node is not returning the disk stats in the filesystem section. Not sure why (could be related to this: [https://github.com/elastic/elasticsearch/issues/24804](https://github.com/elastic/elasticsearch/issues/24804)). submitted pull request to fix
