### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by pengpan** [ElasticHQ/elasticsearch-HQ#303]
Hi
    my es version:5.6.4 and install x-pack，then http  access need username and password；
    when I ordered the connect button，tip 
    `Error!   Unable to Connect to Server! Received Status Code: 401.`
     hope to get reply, very thanks

**Comment by ouyuwo** [comment]
+1,@royrusso

**Comment by royrusso** [comment]
Ah... working on this for v3. So far tests pass for ES 2.x, 5.x, and 6.x. Haven't tested xpack yet. :-(

**Comment by royrusso** [comment]
This is solved in the coming version. In #334
