### ISSUE TITLE
Add cluster information to /status endpoint

### ISSUE THREAD

**Issue by royrusso** [ElasticHQ/elasticsearch-HQ#305]

**Comment by wdm0006** [comment]
I'll work on this. Were you thinking _cluster/health?

**Comment by royrusso** [comment]
Somewhat. There's already a status call under /status. The idea was to add the information in CONNECTIONS to it, like exists for GET /clusters (elastichq.api.clusters.ClusterList). At some point, we may need a ClusterModel, so these endpoints aren't building the cluster responses manually.
