### ISSUE TITLE
ESv6 wrong request headers

### ISSUE THREAD

**Issue by klahnakoski** [ElasticHQ/elasticsearch-HQ#313]
elasticsearch-HQ does not work with Elasticsearch version 6.  Specifically, ES6 is expecting `Content-Type: application/json`, not `Content-Type: application/x-www-form-urlencoded`

**Comment by royrusso** [comment]
currently in development for HQ v3.

**Comment by royrusso** [comment]
Fixed in develop_3_0_0. Not fixing retroactively.
