### ISSUE TITLE
Connect button not working

### ISSUE THREAD

**Issue by rn0** [ElasticHQ/elasticsearch-HQ#32]
Chrome reports:
`Uncaught TypeError: Object http://localhost:9200 has no method 'val'`
in file [elastichq.js:52](https://github.com/royrusso/elasticsearch-HQ/blob/master/js/elastichq.js#L52)

elasticsearch-HQ installed as site plugin

**Comment by hery-168** [comment]
该插件对浏览器的编码好像有要求，你改成utf-8试试
