### ISSUE TITLE
Cannot establish connection

### ISSUE THREAD

**Issue by cemremengu** [ElasticHQ/elasticsearch-HQ#320]
I cannot connect to my instance (it just says it failed). However, using another open-source admin tool, I can connect successfully.

I am using the download distribution with a docker image (docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.2) and `localhost:9200` replies `ok` when I test on browser.

**Comment by royrusso** [comment]
Did you try the format "http://localhost:9200" and did you enable CORS?

**Comment by cemremengu** [comment]
Yes, CORS is configured like it is described and I tried the URL just like you mentioned.

Not sure what's wrong. Anywhere I can get a log or details about the problem?

**Comment by royrusso** [comment]
Simplest way is to look at the console. In Chrome > right-click > Inspect. Then try to connect and see what the error looks like. I don't know the docker image very well, so you can try to simply download the master branch from the main page here and open index.html.

**Comment by cemremengu** [comment]
Docker image is for `elasticsearch`, I am using the master branch for HQ. The console error log says 
`Failed to load resource: the server responded with a status of 403 (Forbidden)`. However, I have the free version of `x-pack` with no authentication. So it should be able to go through without providing user/pass.

**Comment by royrusso** [comment]
A 403, is definitely the server rejecting the request. I have not tested HQ on x-pack, so I don't know what gremlins the ES guys injected there yet.

**Comment by davidbernat** [comment]
I have a similar difficulty. I receive a 404 error:

```
POST http://localhost:5000/api/clusters/_connect 404 (NOT FOUND)
```

```
ERR:  
{data: {…}, status: 404, config: {…}, statusText: "NOT FOUND", headers: ƒ, …}
data: {data: Array(0), status_code: 404, message: null, response_time: 6}
status: 404
headers: ƒ (n)
config:
method: "POST"
transformRequest: [ƒ]
transformResponse: [ƒ]
paramSerializer: ƒ (e)
jsonpCallbackParam: "callback"
url: "api/clusters/_connect"
data: {ip: "localhost", port: "9200", username: "", password: "", use_ssl: false}
timeout: l {$$state: {…}}
headers: {Accept: "application/json, text/plain, */*", Content-Type: "application/json;charset=utf-8"}
__proto__: Object
statusText: "NOT FOUND"
xhrStatus: "complete"
__proto__: Object
```

**Comment by richardjharris** [comment]
Same as above, using Docker. Will try running it directly.

**Comment by T3rm1** [comment]
Same 404 error. Does not work. Why is this issue closed?

**Comment by Dje-Bos** [comment]
Finally, I've resolved the issue as described https://github.com/ElasticHQ/elasticsearch-HQ/issues/419 . You have to replace localhost of your elasctic search cluster with the internal elasticsearch host in docker. For me, it was: http://localhost:9200 ------> http://elastic:9200
