### ISSUE TITLE
Free hosted version seems to be gone

### ISSUE THREAD

**Issue by stof** [ElasticHQ/elasticsearch-HQ#331]
The readme talks about a free hosted version. And http://www.elastichq.org/gettingstarted.html mentions it as well. But I see no way to access it.

**Comment by royrusso** [comment]
Yes. I took it down after folks (quite accurately) complained of the insecure nature of having it hosted on a non ssl domain.

**Comment by stof** [comment]
Then it would be great to update the website to stop referring to it. It creates confusion.

**Comment by royrusso** [comment]
Good point. I updated the top icons and never updated the "Which option is right for me?" section. Thanks.

**Comment by stof** [comment]
And the readme of the repo on github also talks about the hosted version.

**Comment by royrusso** [comment]
should be addressed now. hosted is still gone.
