### ISSUE TITLE
Support for X-Pack and Basic Auth

### ISSUE THREAD

**Issue by royrusso** [ElasticHQ/elasticsearch-HQ#334]

**Comment by priodchen** [comment]
You can use:
http://USERNAME:PASSWORD@DOMAIN:PORT

**Comment by alexizmailov** [comment]
There is still a problem with numeric passwords:
`http://user:12345678@dev-nginx-01:80` results in 
```
 'Unable to create connection to: http://dev-nginx-01.svc.int.ix.org.au:12345678'#015
```
So the password is treated as port if it's numbers only.
