### ISSUE TITLE
reverse proxy at subpath

### ISSUE THREAD

**Issue by colmaengus** [ElasticHQ/elasticsearch-HQ#340]
I would like to be able to serve elastichq behind a reverse proxy using a sub path. For example /debug/elastichq. However index.html is hardcoded to look for static files at /.
I can edit the index.html and work around this but the apis are all called at /api where I need them to be called at /debug/elastichq/api.
Any tips on how to proceed with this ?

**Comment by royrusso** [comment]
I'm thinking something has to be edited in the webpack config, but I'll wait for a UI committer to chime in. I believe there are ways to have the UI proxy and rewrite requests, which may work for you, but can wait until @pcasa chimes in. 

https://webpack.js.org/configuration/dev-server/#devserver-proxy

**Comment by pcasa** [comment]
Are you using NGINX or Apache?  Sounds like you need a re-write rule such as https://www.nginx.com/resources/admin-guide/reverse-proxy/#headers.

**Comment by colmaengus** [comment]
I'm actually using a node.js proxy because I need to include authentication.
It is doing the re-write so the request gets redirected correctly.
However the index.html that comes back contains paths that start with / which means the browser goes looking in the wrong place for the css/js etc.
I tried changing the index.html to use relative paths and this works but the application bundle is still looking for the api at /api. Is there a way to get access to where this is set ?

We've taken a similar approach for lots of other tools and some of them require some extra configuration so that they know what subpath they are being served at and where their API is available at (e.g. graylog, grafana). Others just use relative paths and work transparently behind a proxy.

**Comment by pcasa** [comment]
Can you pull / clone from the develop branch and try?

**Comment by colmaengus** [comment]
@pcasa: what a star ! that works a treat. I've created a docker on our main server and able to access it via our authenticated application.
interesting (and very welcome) that the elasticsearch connection is done by the server so I'm able to connect giving the local elasticsearch connection details even though they aren't externally available.

The diagnostics page is giving a 500 error. What should I expect to see ?
I'm also not seeing any charts e.g. CPU Usage (maybe this is what I'm missing from the diagnostics view)

**Comment by royrusso** [comment]
Can you see the other screens?  Is it only failing on the diagnostics page? If you could look at the log, it  should have a stack trace when you hit the diagnostics screen.

Alternatively, you can trigger the diagnostics API call with a GET call: http://docs.elastichq.org/rest-api.html#cluster-diagnostics

**Comment by colmaengus** [comment]
It's the API call itself that is giving the error. I can see data on the other screens. I'm getting the same error when I call it locally without the proxy.
I'm using elasticsearch 2.1.0. Could this be the issue ? I'll take a look at the logs tomorrow to see if there is anything useful to learn.

**Comment by royrusso** [comment]
It's definitely the python backend. You can adjust the log to use file-based logging instead of console: http://docs.elastichq.org/installation.html#logging

Or pipe the console output to a file, but python's pipe-to-file isn't exactly real-time flushing.

**Comment by colmaengus** [comment]
Is elasticsearch 2.1.0 supported ? When I use a later version (5.3.3) I'm able to see the diagnostics data.
I still can't find any charts like you show in your feature slide show. Can you point me in the right direction ?

**Comment by royrusso** [comment]
Charts are coming. That was an old version of the app that is no longer supported. 

I can test with 2.1.0 and verify. The earliest we test on is 2.4.0. It would be strange if a minor point release would break this, but I wouldn't be surprised. ;-)

**Comment by narraraveendrababu** [comment]
I have configured docker build using ProxyPassReverse from apache2. I can able to see all other dashbaord except metrics module, i tried based on paca thread it is not working.

I am using apache2, setting like 

                ProxyPass /elastichq/ http://localhost:5000/
                ProxyPassReverse /elastichq/(.*) http://localhost:5000/elastichq/(.*)
                RewriteEngine On
                RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
                RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
                RewriteRule .* ws://localhost:5000/elastichq%{REQUEST_URI} [P]

advanced thank you, any suggestion to configure websocket in apache2 for elastichq
