### ISSUE TITLE
Cluster Health in HQ v3 

### ISSUE THREAD

**Issue by artful88533** [ElasticHQ/elasticsearch-HQ#345]
HQ v3 grate dashboard, thanks to everyone who make it! But I have question.
In old version on main page was Cluster Health 
<img width="720" alt="screenshot at mar 04 10-40-33" src="https://user-images.githubusercontent.com/19188399/36943940-ff26e5a0-1f9a-11e8-8661-3bad4af85f25.png">

Can I see statistics with all kind of shards in v3 ?

**Comment by royrusso** [comment]
The cluster health is now part of the name of the cluster.. if the heart icon is in green/yellow/red.

The individual indices now show relocation of shards. The main cluster page still shows if there are shards unassigned.

**Comment by artful88533** [comment]
I don't see unassigned shards on main page.
Could you add to main page total "Relocating Shards", total "Initializing Shards", total "Unassigned Shards". 
I have 350 indicies and when I have some problem with cluster very comfortably see this statistics.

**Comment by royrusso** [comment]
I'll add an issue to make the shard states more obvious. The main page would be a good place to show this.
