### ISSUE TITLE
TBD: Rules/Alerts functionality

### ISSUE THREAD

**Issue by royrusso** [ElasticHQ/elasticsearch-HQ#350]
Rules and alerts for:

- cluster(s) metrics meet some threshold
- indexed documents match some criteria

**Comment by lukas-vlcek** [comment]
Isn't [Prometheus](https://prometheus.io/) better for this job?

**Comment by royrusso** [comment]
Hard to know if it's "better", if we haven't built this functionality yet. ;-) 

The goal is to make HQ the *one* ES dashboard without having to cobble together (and pay for) x-pack, promethues, security plugins, etc...

**Comment by royrusso** [comment]
Something to consider is integrating the python work from the Yelp guys: https://github.com/Yelp/elastalert 

It's simple alerting that just works.

**Comment by lukas-vlcek** [comment]
Prometheus is fully open source and part of [CNCF](https://www.cncf.io/). It is used for monitoring in clouds a lot (supports Kubernetes for example) and it gives you great alerting capabilities as well. I recommend you to check some of the latest talks about it to see if you plan to aim at this level of monitoring and alerting. May be you can save a lot of cycles by focusing on different aspects of ElasticHQ instead. Prometheus is also very well supported by Grafana if you want fancy dashboarding on top of operational stats pulled from Elasticsearch.

**Comment by royrusso** [comment]
I'll take some time to look at it. It's been a while since I last evaluated it.

**Comment by lukas-vlcek** [comment]
May be you should consider implementing endpoint for ElasticHQ integration for Prometheus :-) But seriously, if you plan HQ to be run in clouds alongside ES clusters then users will require monitoring of HQ too.

**Comment by royrusso** [comment]
@lukas-vlcek This reminds me of how RHT sells support contracts. ;-) 

That's a good point on prometheus integration. Current hosting companies (not Elastic) running HQ are using AWS monitoring, but still a good idea.

**Comment by lukas-vlcek** [comment]
I am not selling you anything :-)
I just think beating Prometheus in its own territory will take a lot of energy which can be invested into unique HQ features instead.

**Comment by royrusso** [comment]
Somewhat agree... The idea still needs to be fleshed out. I see HQ more evolving as an alternative to paid (and free) X-Pack more than anything else. Specifically for alerting, it's Watcher (https://www.elastic.co/guide/en/x-pack/current/watcher-getting-started.html) that I'm targeting.

**Comment by lukas-vlcek** [comment]
There are plenty of Prometheus talks on youtube, out of many I found this one interesting recently: [PromCon 2016: Alerting in the Prometheus Universe - Fabian Reinartz](https://www.youtube.com/watch?v=yrK6z3fpu1E)
