### ISSUE TITLE
Sqlite constraints problems

### ISSUE THREAD

**Issue by borlafdev** [ElasticHQ/elasticsearch-HQ#355]
Hi, 

I just cloned the repo, started the app and filled the cluster url in the gui, 500 response, search the logs, cluster table has a not null constraint and cluster.name is empty, ok, sqlite3 elastichq.db, i delete the constrain... But cluster name is primary key and there is no cluster name field in the gui... Why?

I suppose you are testing new version, but the readme and the docs indicates nothing.

**Comment by royrusso** [comment]
The app needs the cluster name to uniquely identify the cluster(s).

What version of ES? What is returned using `curl -XGET http://IP:PORT`?

The response from that, determines the cluster name inserted in to the DB.

**Comment by borlafdev** [comment]
1.3.3 just realized that is unsupported, sorry for wasting your time.

**Comment by royrusso** [comment]
Not a waste. Thanks.
