### ISSUE TITLE
Runing the command for server ./manage.py runserver 

### ISSUE THREAD

**Issue by hariprasadkool** [ElasticHQ/elasticsearch-HQ#359]
Runing the command for server ./manage.py runserver

./manage.py runserver
./manage.py: line 4: __author__: command not found
from: can't read /var/mail/flask_migrate
from: can't read /var/mail/flask_script
from: can't read /var/mail/elastichq.factory
from: can't read /var/mail/elastichq.globals
./manage.py: line 14: syntax error near unexpected token `('
./manage.py: line 14: `app = create_app()'

**Comment by royrusso** [comment]
Try: `python manage.py runserver`

**Comment by hariprasadkool** [comment]
thanks for the fix
