### ISSUE TITLE
Docker Image serves content but errors on nearly all API calls

### ISSUE THREAD

**Issue by ronnyek** [ElasticHQ/elasticsearch-HQ#360]
### General information

- **OS Platform and Distribution: Docker
- **ElasticHQ Version**: latest
- **Elasticsearch Version**: 5.3.2
- **Python version**: whatever is in docker image
- **Browser Vendor and Version (if applicable)**: chrome

### Issue Description

Spun up a new docker instance of this, and forwarded port 5000.

I accessed the url at which ui should be published. I get the connection screen where I specify connection information as:
http://<user>:<pass>@domain:<port>

Upon hitting connect, I get a connected successfully and then a whole bunch of popups about not being able to load information from indicies.

Javascript console provides a ton of these:

```
Possibly unhandled rejection: {"data":{"message":"Oops! Something bad happened.","status_code":500},"status":500,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"api/clusters/docker-cluster/_summary","timeout":{},"headers":{"Accept":"application/json, text/plain, */*"}},"statusText":"INTERNAL SERVER ERROR","xhrStatus":"complete"}
```

The docker console doesn't show much in the way of errors so I cant see if its that my elasticsearch server is mis-configured or anything.

Should the new version of elastichq require cors still? Also could it be that having basic authentication is breaking it?

**Comment by royrusso** [comment]
No need for CORS anymore. If you're using basic auth, that would explain the issue: http://docs.elastichq.org/user-guide.html#initial-login

`http://USERNAME:PASSWORD@DOMAIN:PORT`

I'll look in to how to expose the app logs so folks using the docker image can tail them.

**Comment by ronnyek** [comment]
That's actually the format of the url I used... My pseudo syntax broke markdown. It acts like it's connecting. I'd be more than happy to help troubleshoot.. I saw where logging was specified in logging.conf... but 0 experience with whatever webserver is being used there.

**Comment by royrusso** [comment]
It looks like you can turn on the file logger by shelling in the docker instance and following this: http://docs.elastichq.org/installation.html#logging

Basically, "standard_handler" will log to a file that you can tail under `/src/application.log`. `vi` will work in the docker instance.

I'll open an issue to either turn that on by default or somehow pipe it somewhere more obvious for docker users.

**Comment by ronnyek** [comment]
Just as a comment for others... this ended up being related to elastic instance having expired license for "security" feature from xpack
