### ISSUE TITLE
Feature Request: Allow default connection to be changed

### ISSUE THREAD

**Issue by scottgeary** [ElasticHQ/elasticsearch-HQ#361]
### General information

- **ElasticHQ Version**: 3+

### Feature Description

When starting the python server for the first time, the ES connection setting is `http://localhost:9200`. This is great if ES is running locally (always the case in the old plugin approach), however, when running in-container, it's highly likely you'll need to type in something specific to your setup. 

![image](https://user-images.githubusercontent.com/6138868/37800141-ca354d28-2e86-11e8-8904-98878e5bcca0.png)

Compiling unique frontend code isn't really a great approach, or trying to adjust the static content on the way to the client. So perhaps the frontend code could additionally make an API to the server to receive any overridden connection string?

Suggested way to start the server:

```
$ sudo docker run --env HQ_DEFAULT_CONNECTION="http://my_really_long_aws_load_balancer:9200" -P 3d3e680a6031
2018-03-22 21:51:00,883 CRIT Supervisor running as root (no user in config file)
…
```

It could also be a command-line param, or even a config file too. This would cover all use cases :)

### Source Code / Logs

The value is currently hardcoded into the compiled JS code at: https://github.com/ElasticHQ/elasticsearch-HQ/blob/f8203f7850d32178401e477c51525eb87ff0f27b/ui/src/containers/home/home.controller.js#L15

Flask serves up the static assets here:
https://github.com/ElasticHQ/elasticsearch-HQ/blob/f8203f7850d32178401e477c51525eb87ff0f27b/elastichq/api/__init__.py#L17

Sorry that I couldn't offer a PR: A little unfamiliar with Flask or what the best approach would be.

**Comment by royrusso** [comment]
That's a fair request. I'm not sure if you know this, but the application will store all previously connected clusters and they are accessible from the dropdown on the initial page.

**Comment by scottgeary** [comment]
Yeah, love the cluster section :)

However, the way some clusters are managed means frequent restarts, and no persisted storage. So that local sqlalchemy db gets blown away.

**Comment by royrusso** [comment]
Got it. I'll see if this can make the next release.

**Comment by tc-turner** [comment]
Is it possible to define the default connection via URL query params?

We use a single HQ to connect to multiple ES clusters with the same name so the cluster feature lumps all connections together it seems.  If we could use a bookmark like:

`http://my-hq-box.com/?ip=one-es-cluster:9200` that would be awesome :)

**Comment by royrusso** [comment]
@tc-turner I wrestled with this initially, but couldn't find an elegant solution... HQ keeps a record of all clusters in a local database, using the cluster_name as the primary key.

**Comment by tc-turner** [comment]
@royrusso  thanks for the reply.  I understand, since our usage is against the grain I will work on figuring out how to run multipl HQ containers behind nginx.
