### ISSUE TITLE
Add a Docker option to pass CA file (for self-signed CA)

### ISSUE THREAD

**Issue by C-Duv** [ElasticHQ/elasticsearch-HQ#377]
Using Docker image (15906219235d) I fail to connect to my Elasticsearch via HTTPS using an internal (non-public, non-trusted, self-signed) CA.
It works if I connect on the HTTP endpoint.

Please a Docker environment variable, option or other so that I can pass my CA's public certificate to the Docker container and that it adds it to it's list of trusted certificates.

**Comment by royrusso** [comment]
This should be in master and the latest release now.

- HQ_ENABLE_SSL: If flag is passed, assumes ssl cert will be used.
- HQ_CA_CERTS: /path/to/your/ca.crt  Path to your CA Certificate. Required if enable-ssl is passed.
