### ISSUE TITLE
Question about Diagnostics

### ISSUE THREAD

**Issue by ZhiqiangTao** [ElasticHQ/elasticsearch-HQ#388]
![image](https://user-images.githubusercontent.com/16182251/39294818-48069434-496f-11e8-8f2b-b39102f70e4f.png)

Hi, I'm not sure what's the meaning of the **yellow** data? is it bad health?
but you can see that another same node is no color

**Comment by royrusso** [comment]
Mouseover and it should say. That being said, the values you have there are nothing to worry about. If you see a red block, then definitely look closer.

**Comment by ZhiqiangTao** [comment]
Thank you :grinning:
