### ISSUE TITLE
Bug: Password are html encoded

### ISSUE THREAD

**Issue by danielmotaleite** [ElasticHQ/elasticsearch-HQ#389]
### General information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian Stretch
- **ElasticHQ Version**: 3.3.0 (using elastichq/elasticsearch-hq:latest docker hub image)
- **Elasticsearch Version**: 5.6.7
- **Python version**:  using elastichq/elasticsearch-hq:latest, so whatever is included :)
- **Browser Vendor and Version (if applicable)**: firefox 60b16

### Issue Description
Using the HQ docker, i can connect to it and it looks almost that it works, but many requests return "500 internal server error". With a little debug i found that the ES is returning auth denied yet it reports a login attempt with my user. After a tcpdump, i grab the authorization basic header and decoding it i could see that one character in the password ( "=" ) gets converted to %3D.

I added the cluster with the http://username:password@ES_address:9200 and it is accepted and the proof is that the authorization header is there... just the passwords gets encoded when calculating the basic authentication header and so breaking the authorization check

i do not even know why the = is encoded, as it is not usually to do that and i didn't tested with other characters, like special characters or local characters

Thanks for HQ!

**Comment by royrusso** [comment]
I'll look at this. It could be how we're using the requests library.

**Comment by royrusso** [comment]
That makes sense. The @ is used as a separator.

**Comment by danielmotaleite** [comment]
yep, that one is harder, the @ in the password conflict with the @ separator in basic auth
In the [RFC](https://tools.ietf.org/html/rfc2617#page-6) , they do not impose restrictions, but to use basic auth in the url, the @  can't be used

**Comment by royrusso** [comment]
Yes. The html encoding, I will handle in this next release (3.5.0). Passwords with "@" will be tricky if I can fix, at all.

**Comment by danielmotaleite** [comment]
Working fine now, thanks!
