### ISSUE TITLE
Question about Diagnostics

### ISSUE THREAD

**Issue by ashashwat** [ElasticHQ/elasticsearch-HQ#393]
![screen shot 2018-05-18 at 4 31 49 pm](https://user-images.githubusercontent.com/121233/40231680-aaf65da8-5ab9-11e8-8699-b26ad8e37a9c.png)

I am exploring elasticsearch-HQ.  There is a slight bit of confusion regarding this graph.  Does this mean one of my nodes has 100 % failure rate?  If that is the case cluster health should show an issue, right?

**Comment by royrusso** [comment]
The decimals on that chart are deceiving. What it shows, is that there has been only one indexing failure. You may want to check the ES log for more info, but no... your cluster doesn't appear to be failing.

**Comment by ashashwat** [comment]
Thanks @royrusso
