### ISSUE TITLE
Latest docker image is broken

### ISSUE THREAD

**Issue by yaningzhu** [ElasticHQ/elasticsearch-HQ#400]
### General information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS High Sierra
- **ElasticHQ Docker Image Version**: Latest, think it's 3.4?
- **Docker Version**: 18.03.1-ce

### Issue Description

The Docker image simply doesn't work. 

**Steps to reproduce**:

1. Pull Docker image

    ```
    docker pull elastichq/elasticsearch-hq
    docker run -p 5000:5000 elastichq/elasticsearch-hq
    ```

2. Then visit http://localhost:5000 in web browser. You get a blank screen.

The same procedure works fine when using the `release-v3.3.0` image as oppose to `latest`.

**Comment by royrusso** [comment]
I'm not able to reproduce this issue. Pull and run bound to port 5000 work fine.

> Login Succeeded
loki:Downloads royrusso$ docker pull elastichq/elasticsearch-hq
Using default tag: latest
latest: Pulling from elastichq/elasticsearch-hq
Digest: sha256:0221d61fef2d6c6ddec48e65d6dc7aae8ff1ccf559d3088c2725607c0fd41b9f
Status: Image is up to date for elastichq/elasticsearch-hq:latest
loki:Downloads royrusso$ docker run -p 5000:5000 elastichq/elasticsearch-hq
2018-06-03 01:56:51,036 CRIT Supervisor running as root (no user in config file)
2018-06-03 01:56:51,037 INFO supervisord started with pid 1
2018-06-03 01:56:52,044 INFO spawned: 'gunicorn' with pid 9
2018-06-03 01:56:53,820 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by yaningzhu** [comment]
I tested this further. Turns out it's only broken in Safari. I can work around this for now. But let me know if you want another issue open.

**Comment by royrusso** [comment]
I'll reopen and test in Safari. Thanks.

**Comment by royrusso** [comment]
Going to close for now, unless I see someone else complain for Safari. I tested on Version 11.1 (13605.1.33.1.4), and is working fine on HQ 3.4.0

**Comment by lanwin** [comment]
I can confirm this future. Docker release-v3.4.0 produces a blank page. I saw the error "invalid chunk encoding" in my browsers log. Tested in latest Chrome and latest Firefox.

It works Docker release-v3.3.0.

**Comment by sebastien-prudhomme** [comment]
Same bug for me with release-v3.4.0. All is OK with release-v3.3.0.

My environment : ElasticHQ behind Traefik reverse proxy.

The main.xxxxx.js file can't be downloaded correctly.

Without Traefik proxy, all is OK

```
curl http://localhost:5000/static/main.8f8008bdb0d1843e5c8c.js -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2389k  100 2389k    0     0   233M      0 --:--:-- --:--:-- --:--:--  259M
```

With Traefik proxy, it is not OK

```
curl http://my-external-url/static/main.8f8008bdb0d1843e5c8c.js -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  1 2389k    1 39092    0     0  1683k      0  0:00:01 --:--:--  0:00:01 1735k
curl: (18) transfer closed with 2407788 bytes remaining to read
```

Traefik logs:

```
X.X.X.X - - [21/Jun/2018:07:52:39 +0000] "GET /static/main.8f8008bdb0d1843e5c8c.js HTTP/1.1" 200 39092 "-" "curl/7.29.0" 674989 "elastichq" "http://Y.Y.Y.Y:5000" 6ms
2018/06/21 07:52:39 reverseproxy.go:321: httputil: ReverseProxy read error during body copy: unexpected EOF
```

If i launch the Docker image without the default CMD (supervisord + gunicorn) and only "python src/application.py", all is working fine.

So i guess the problem comes from gunicorn integration.

**Comment by kamax7C0** [comment]
Same here with v3.4.0, Ubuntu 18 and Firefox, the main.8f8008bdb0d1843e5c8c.js is not being fully loaded, when served from a docker container. Hitting F5 5-6 times loads it finally, but another F5 may break it again. Same does **not** happen with release-3.3.0 .  
Application.log shows nothing when it happens.  

It looks like this is what's happening - https://github.com/benoitc/gunicorn/issues/1155

**Comment by royrusso** [comment]
May be related to #365 ?

**Comment by chrisLeeTW** [comment]
seems if you reverse gunicorn version to 19.4.5 and every thing works fine. tests with elastichq/elasticsearch-hq:release-v3.4.0

**Comment by royrusso** [comment]
I will revert and test.

**Comment by royrusso** [comment]
I just pushed a release. If the master branch continues to have the same problem, I'll reopen this ticket and make the change to the gunicorn version.
