### ISSUE TITLE
Use x-pack，and HQ can't connect to es.

### ISSUE THREAD

**Issue by priodchen** [ElasticHQ/elasticsearch-HQ#402]
### General information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Centos : 6.8
- **ElasticHQ Version**:
lastest version
- **Elasticsearch Version**:
elasticsearch : 6.2.3
- **Python version**:
Python 3.6.5 
- **Browser Vendor and Version (if applicable)**:

### Issue Description

Use x-pack，and elasticsearch-HQ can't connect to es.

How can I config it to connect es? Thanks!

**Comment by royrusso** [comment]
http://docs.elastichq.org/installation.html#x-pack-integration
