### ISSUE TITLE
 attempt to write a readonly database

### ISSUE THREAD

**Issue by KlavsKlavsen** [ElasticHQ/elasticsearch-HQ#403]
python 3.5, elastichq 3.4.0..

I run daemon as nobody user..The error message is from when I try to add cluster config..
it seems it defaults to putting its sqlite3 db smack in the middle of the python ..
/usr/share/python/elasticsearch-hq/lib/python3.5/site-packages/elastichq.db

I could not find any settings example file..i assume I can tell it which DB to use, where to store sqlite3 db etc.?

**Comment by KlavsKlavsen** [comment]
(it says it tries to load /etc/elastichq/settings.json)

**Comment by KlavsKlavsen** [comment]
i had to switch to running it as root user it to work :(

**Comment by royrusso** [comment]
This is strange... the elastichq.db is normally created where the code is running, so local. Typically this is at the same level as application.py. I find it strange that it's attempting to create it where the imports are in site-packages.

**Comment by KlavsKlavsen** [comment]
its probably because I created a systemd service file to run it.. it really should load a config file, to tell it where to put its data, so one can make sure the user it runs as, can write to that folder.

**Comment by wdm0006** [comment]
@KlavsKlavsen you should actually be able to do that already, if you write a `settings.json` file with the sqlite db specified in `SQLALCHEMY_DATABASE_URI` as wherever you want the path to be. You can put that file in `~` or in `/etc/elastic-hq`.

**Comment by KlavsKlavsen** [comment]
And could you give an example of such a settings.json file? how should it look - what parameters can I set there?

**Comment by royrusso** [comment]
I will add this to the online docs, once I get an example working.
