### ISSUE TITLE
ImportError: cannot import name 'Namespace'

### ISSUE THREAD

**Issue by Moebius2722** [ElasticHQ/elasticsearch-HQ#408]
### General information

- **Rapsbian 4.14**:
- **ElasticHQ Master Branch**:
- **Elasticsearch 6.3.0 OSS**:
- **Python 3.5.3**: 
- **Chrome 67.0.3396.99 (Build officiel) (64 bits)**:

### Issue Description
After install ElasticHQ on my raspberry pi 3 B+ : "sudo git clone https://github.com/ElasticHQ/elasticsearch-HQ /usr/share/elastichq"
When run "sudo python3 application.py" in "/usr/share/elastichq" 
I've error "ImportError: cannot import name 'Namespace'"

### Source Code / Logs

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    from elastichq import create_app
  File "/usr/share/elastichq/elastichq/__init__.py", line 5, in <module>
    from elastichq.api import api_blueprint, endpoints, public_blueprint, ws_blueprint
  File "/usr/share/elastichq/elastichq/api/endpoints.py", line 4, in <module>
    from . import clusters
  File "/usr/share/elastichq/elastichq/api/clusters.py", line 11, in <module>
    from elastichq.model import ClusterDTO
  File "/usr/share/elastichq/elastichq/model/__init__.py", line 3, in <module>
    from elastichq.model.ClusterModel import *
  File "/usr/share/elastichq/elastichq/model/ClusterModel.py", line 7, in <module>
    from ..globals import db, ma
  File "/usr/share/elastichq/elastichq/globals.py", line 11, in <module>
    from flask_socketio import SocketIO
  File "/usr/local/lib/python3.5/dist-packages/flask_socketio/__init__.py", line 23, in <module>
    from .namespace import Namespace
  File "/usr/local/lib/python3.5/dist-packages/flask_socketio/namespace.py", line 1, in <module>
    from socketio import Namespace as _Namespace
ImportError: cannot import name 'Namespace'

**Comment by royrusso** [comment]
May be a silly question, but did you install requirements? I didn't see that in your comment.

http://docs.elastichq.org/installation.html#install-elastichq

**Comment by Moebius2722** [comment]
Yes, I'm run "sudo pip3 install -r requirements.txt" in "/usr/share/elastichq"
Attention, I'm on a Raspberry Pi with a SOC ARM.

**"sudo pip3 install -r requirements.txt" result :**

Collecting jmespath==0.9.3 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/b7/31/05c8d001f7f87f0f07289a5fc0fc3832e9a57f2dbd4d3b0fee70e0d51365/jmespath-0.9.3-py2.py3-none-any.whl
Collecting Flask==0.12.2 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/77/32/e3597cb19ffffe724ad4bf0beca4153419918e7fa4ba6a34b04ee4da3371/Flask-0.12.2-py2.py3-none-any.whl (83kB)
    100% |████████████████████████████████| 92kB 417kB/s
Collecting Flask-restful==0.3.6 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/47/08/89cf8594735392cd71752f7cf159fa63765eac3e11b0da4324cdfeaea137/Flask_RESTful-0.3.6-py2.py3-none-any.whl
Collecting Flask-Script==2.0.6 (from -r requirements.txt (line 6))
  Downloading https://www.piwheels.org/simple/flask-script/Flask_Script-2.0.6-py3-none-any.whl
Collecting flask-marshmallow==0.8.0 (from -r requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/c5/8a/63d455ddea52287766fb4c2d8a02698a4126dd1bf3325a04fedb8bab64b0/flask_marshmallow-0.8.0-py2.py3-none-any.whl
Collecting marshmallow-sqlalchemy==0.13.2 (from -r requirements.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/c4/9d/04da2c85be887812a0b763f846bde60860e75556e469e5c769f18fc0ccf8/marshmallow_sqlalchemy-0.13.2-py2.py3-none-any.whl
Collecting marshmallow==3.0.0b5 (from -r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/7f/31/a9e75aa74347bdefc078ed61e33ba6e2ba8c38d78f6578204ce300c11ff8/marshmallow-3.0.0b5-py2.py3-none-any.whl (44kB)
    100% |████████████████████████████████| 51kB 452kB/s
Collecting urllib3<1.23,>=1.21.1 (from -r requirements.txt (line 14))
  Downloading https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 377kB/s
Collecting requests<3.0.0,>=2.0.0 (from -r requirements.txt (line 15))
  Downloading https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl (91kB)
    100% |████████████████████████████████| 92kB 394kB/s
Collecting dogpile.cache==0.6.5 (from -r requirements.txt (line 18))
  Downloading https://www.piwheels.org/simple/dogpile-cache/dogpile.cache-0.6.5-py2.py3-none-any.whl (44kB)
    100% |████████████████████████████████| 51kB 448kB/s
Collecting SQLAlchemy==1.2.0 (from -r requirements.txt (line 21))
  Downloading https://www.piwheels.org/simple/sqlalchemy/SQLAlchemy-1.2.0-cp35-cp35m-linux_armv7l.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 167kB/s
Collecting Flask-SQLAlchemy==2.3.2 (from -r requirements.txt (line 22))
  Downloading https://files.pythonhosted.org/packages/a1/44/294fb7f6bf49cc7224417cd0637018db9fee0729b4fe166e43e2bbb1f1c8/Flask_SQLAlchemy-2.3.2-py2.py3-none-any.whl
Collecting Flask-Migrate (from -r requirements.txt (line 23))
  Downloading https://files.pythonhosted.org/packages/59/97/f681c9e43d2e2ace4881fa588d847cc25f47cc98f7400e237805d20d6f79/Flask_Migrate-2.2.1-py2.py3-none-any.whl
Collecting coverage==3.7.1 (from -r requirements.txt (line 26))
  Downloading https://www.piwheels.org/simple/coverage/coverage-3.7.1-cp35-cp35m-linux_armv7l.whl (129kB)
    100% |████████████████████████████████| 133kB 415kB/s
Collecting nose==1.3.4 (from -r requirements.txt (line 27))
  Downloading https://files.pythonhosted.org/packages/07/c6/0667b318b01832320829b32b9858bc8897710b373d3f7c88a0e6fca742e9/nose-1.3.4-py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 408kB/s
Collecting Flask-Testing (from -r requirements.txt (line 28))
  Downloading https://www.piwheels.org/simple/flask-testing/Flask_Testing-0.7.1-py3-none-any.whl
Collecting pytest==3.0.2 (from -r requirements.txt (line 29))
  Downloading https://files.pythonhosted.org/packages/c4/bf/80d1cd053b1c86f6ecb23300fba3a7c572419b5edc155da0f3f104d42775/pytest-3.0.2-py2.py3-none-any.whl (169kB)
    100% |████████████████████████████████| 174kB 439kB/s
Collecting pytest-cov==2.3.1 (from -r requirements.txt (line 30))
  Downloading https://files.pythonhosted.org/packages/67/94/93dd3288f9a6accfc25e4c636aa912824a2e66d08a464d6f62421da8742f/pytest_cov-2.3.1-py2.py3-none-any.whl
Collecting pytest-ordering==0.5 (from -r requirements.txt (line 31))
  Downloading https://files.pythonhosted.org/packages/a3/f1/4555cfdfc8a36fed76a1cc23922c39310a51d334eaae2e2cb45551e62070/pytest_ordering-0.5-py2.py3-none-any.whl
Collecting apscheduler==3.5.0 (from -r requirements.txt (line 35))
  Downloading https://files.pythonhosted.org/packages/19/d9/ca8322005bcd84c38e38cfaf2d5bd6fb66c14b4e977e973c6bb5ac5b98c7/APScheduler-3.5.0-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 409kB/s
Collecting Flask-APScheduler==1.7.1 (from -r requirements.txt (line 36))
  Downloading https://www.piwheels.org/simple/flask-apscheduler/Flask_APScheduler-1.7.1-py3-none-any.whl
Collecting python-engineio==2.0.2 (from -r requirements.txt (line 39))
  Downloading https://files.pythonhosted.org/packages/c3/5a/316c1d956e229a9d5a80db842261922ea95a073d91d1402951c66bad7963/python_engineio-2.0.2-py2.py3-none-any.whl
Collecting Flask-SocketIO==2.9.4 (from -r requirements.txt (line 40))
  Downloading https://files.pythonhosted.org/packages/38/3c/8f45c5b309cc809b82bd9d7dd79a686429eeffac221c1acdff84a13e9daf/Flask_SocketIO-2.9.4-py2.py3-none-any.whl
Collecting eventlet==0.22.1 (from -r requirements.txt (line 41))
  Downloading https://files.pythonhosted.org/packages/61/1a/d1ff6e4f1dc652dfdda4a674f807c842eaa15f1ed9b76938a3be313bbac9/eventlet-0.22.1-py2.py3-none-any.whl (409kB)
    100% |████████████████████████████████| 409kB 269kB/s
Collecting six==1.11.0 (from -r requirements.txt (line 47))
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting python-dateutil==2.7.2 (from -r requirements.txt (line 48))
  Downloading https://files.pythonhosted.org/packages/0c/57/19f3a65bcf6d5be570ee8c35a5398496e10a0ddcbc95393b2d17f86aaaf8/python_dateutil-2.7.2-py2.py3-none-any.whl (212kB)
    100% |████████████████████████████████| 215kB 316kB/s
Collecting Jinja2>=2.4 (from Flask==0.12.2->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl (126kB)
    100% |████████████████████████████████| 133kB 344kB/s
Collecting click>=2.0 (from Flask==0.12.2->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl (71kB)
    100% |████████████████████████████████| 71kB 408kB/s
Collecting Werkzeug>=0.7 (from Flask==0.12.2->-r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl (322kB)
    100% |████████████████████████████████| 327kB 324kB/s
Collecting itsdangerous>=0.21 (from Flask==0.12.2->-r requirements.txt (line 4))
  Downloading https://www.piwheels.org/simple/itsdangerous/itsdangerous-0.24-py3-none-any.whl
Collecting pytz (from Flask-restful==0.3.6->-r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl (510kB)
    100% |████████████████████████████████| 512kB 281kB/s
Collecting aniso8601>=0.82 (from Flask-restful==0.3.6->-r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/17/13/eecdcc638c0ea3b105ebb62ff4e76914a744ef1b6f308651dbed368c6c01/aniso8601-3.0.2-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests<3.0.0,>=2.0.0->-r requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests<3.0.0,>=2.0.0->-r requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.0.0->-r requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting alembic>=0.7 (from Flask-Migrate->-r requirements.txt (line 23))
  Downloading https://www.piwheels.org/simple/alembic/alembic-0.9.10-py2.py3-none-any.whl (155kB)
    100% |████████████████████████████████| 163kB 341kB/s
Collecting py>=1.4.29 (from pytest==3.0.2->-r requirements.txt (line 29))
  Downloading https://files.pythonhosted.org/packages/f3/bd/83369ff2dee18f22f27d16b78dd651e8939825af5f8b0b83c38729069962/py-1.5.4-py2.py3-none-any.whl (83kB)
    100% |████████████████████████████████| 92kB 485kB/s
Collecting tzlocal>=1.2 (from apscheduler==3.5.0->-r requirements.txt (line 35))
  Downloading https://www.piwheels.org/simple/tzlocal/tzlocal-1.5.1-py3-none-any.whl
Requirement already satisfied: setuptools>=0.7 in /usr/lib/python3/dist-packages (from apscheduler==3.5.0->-r requirements.txt (line 35))
Collecting python-socketio>=1.6.1 (from Flask-SocketIO==2.9.4->-r requirements.txt (line 40))
  Downloading https://files.pythonhosted.org/packages/45/c5/29e84a694fadea5864ef9530fe815512764497205b4880be32efefbb607f/python_socketio-2.0.0-py2.py3-none-any.whl
Collecting greenlet>=0.3 (from eventlet==0.22.1->-r requirements.txt (line 41))
  Downloading https://www.piwheels.org/simple/greenlet/greenlet-0.4.13-cp35-cp35m-linux_armv7l.whl (41kB)
    100% |████████████████████████████████| 51kB 487kB/s
Collecting MarkupSafe>=0.23 (from Jinja2>=2.4->Flask==0.12.2->-r requirements.txt (line 4))
  Downloading https://www.piwheels.org/simple/markupsafe/MarkupSafe-1.0-cp35-cp35m-linux_armv7l.whl
Collecting Mako (from alembic>=0.7->Flask-Migrate->-r requirements.txt (line 23))
  Downloading https://www.piwheels.org/simple/mako/Mako-1.0.7-py3-none-any.whl (77kB)
    100% |████████████████████████████████| 81kB 434kB/s
Collecting python-editor>=0.3 (from alembic>=0.7->Flask-Migrate->-r requirements.txt (line 23))
  Downloading https://files.pythonhosted.org/packages/65/1e/adf6e000ea5dc909aa420352d6ba37f16434c8a3c2fa030445411a1ed545/python-editor-1.0.3.tar.gz
Building wheels for collected packages: python-editor
  Running setup.py bdist_wheel for python-editor ... done
  Stored in directory: /root/.cache/pip/wheels/36/e0/98/ba386b125a00ea9dd52e2c16aa2ec0adbbd639b84bfe2e001d
Successfully built python-editor
Installing collected packages: jmespath, MarkupSafe, Jinja2, click, Werkzeug, itsdangerous, Flask, pytz, six, aniso8601, Flask-restful, Flask-Script, marshmallow, flask-marshmallow, SQLAlchemy, marshmallow-sqlalchemy, urllib3, idna, chardet, certifi, requests, dogpile.cache, Flask-SQLAlchemy, Mako, python-editor, python-dateutil, alembic, Flask-Migrate, coverage, nose, Flask-Testing, py, pytest, pytest-cov, pytest-ordering, tzlocal, apscheduler, Flask-APScheduler, python-engineio, python-socketio, Flask-SocketIO, greenlet, eventlet
  Found existing installation: six 1.10.0
    Not uninstalling six at /usr/lib/python3/dist-packages, outside environment /usr
  Found existing installation: idna 2.2
    Not uninstalling idna at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed Flask-0.12.2 Flask-APScheduler-1.7.1 Flask-Migrate-2.2.1 Flask-SQLAlchemy-2.3.2 Flask-Script-2.0.6 Flask-SocketIO-2.9.4 Flask-Testing-0.7.1 Flask-restful-0.3.6 Jinja2-2.10 Mako-1.0.7 MarkupSafe-1.0 SQLAlchemy-1.2.0 Werkzeug-0.14.1 alembic-0.9.10 aniso8601-3.0.2 apscheduler-3.5.0 certifi-2018.4.16 chardet-3.0.4 click-6.7 coverage-3.7.1 dogpile.cache-0.6.5 eventlet-0.22.1 flask-marshmallow-0.8.0 greenlet-0.4.13 idna-2.7 itsdangerous-0.24 jmespath-0.9.3 marshmallow-3.0.0b5 marshmallow-sqlalchemy-0.13.2 nose-1.3.4 py-1.5.4 pytest-3.0.2 pytest-cov-2.3.1 pytest-ordering-0.5 python-dateutil-2.7.2 python-editor-1.0.3 python-engineio-2.0.2 python-socketio-2.0.0 pytz-2018.5 requests-2.19.1 six-1.11.0 tzlocal-1.5.1 urllib3-1.22

**First error after install :**

Traceback (most recent call last):
  File "application.py", line 5, in <module>
    from elastichq import create_app
  File "/usr/share/elastichq/elastichq/__init__.py", line 5, in <module>
    from elastichq.api import api_blueprint, endpoints, public_blueprint, ws_blueprint
  File "/usr/share/elastichq/elastichq/api/endpoints.py", line 4, in <module>
    from . import clusters
  File "/usr/share/elastichq/elastichq/api/clusters.py", line 11, in <module>
    from elastichq.model import ClusterDTO
  File "/usr/share/elastichq/elastichq/model/__init__.py", line 3, in <module>
    from elastichq.model.ClusterModel import *
  File "/usr/share/elastichq/elastichq/model/ClusterModel.py", line 7, in <module>
    from ..globals import db, ma
  File "/usr/share/elastichq/elastichq/globals.py", line 11, in <module>
    from flask_socketio import SocketIO
  File "/usr/local/lib/python3.5/dist-packages/flask_socketio/__init__.py", line 16, in <module>
    import socketio
  File "/usr/local/lib/python3.5/dist-packages/socketio/__init__.py", line 11, in <module>
    from .tornado import get_tornado_handler
  File "/usr/local/lib/python3.5/dist-packages/socketio/tornado.py", line 3, in <module>
    from engineio.async_tornado import get_tornado_handler as \
ImportError: No module named 'engineio.async_tornado'

**"sudo pip3 install socketio" result :**

Collecting socketio
  Downloading https://www.piwheels.org/simple/socketio/socketio-0.1.3-py3-none-any.whl
Collecting netifaces==0.10.6 (from socketio)
  Downloading https://www.piwheels.org/simple/netifaces/netifaces-0.10.6-cp35-cp35m-linux_armv7l.whl (40kB)
    100% |████████████████████████████████| 40kB 432kB/s
Collecting setuptools==3.3 (from socketio)
  Downloading https://files.pythonhosted.org/packages/fc/20/0b304ea9830d53c9068e1e96bbf1ee529283f96ee0ee6ccaaa697f7b2383/setuptools-3.3-py2.py3-none-any.whl (545kB)
    100% |████████████████████████████████| 552kB 264kB/s
Installing collected packages: netifaces, setuptools, socketio
  Found existing installation: setuptools 33.1.1
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed netifaces-0.10.6 setuptools-3.3 socketio-0.1.3

**Error after install SocketIO :**

Traceback (most recent call last):
  File "application.py", line 5, in <module>
    from elastichq import create_app
  File "/usr/share/elastichq/elastichq/__init__.py", line 5, in <module>
    from elastichq.api import api_blueprint, endpoints, public_blueprint, ws_blueprint
  File "/usr/share/elastichq/elastichq/api/endpoints.py", line 4, in <module>
    from . import clusters
  File "/usr/share/elastichq/elastichq/api/clusters.py", line 11, in <module>
    from elastichq.model import ClusterDTO
  File "/usr/share/elastichq/elastichq/model/__init__.py", line 3, in <module>
    from elastichq.model.ClusterModel import *
  File "/usr/share/elastichq/elastichq/model/ClusterModel.py", line 7, in <module>
    from ..globals import db, ma
  File "/usr/share/elastichq/elastichq/globals.py", line 11, in <module>
    from flask_socketio import SocketIO
  File "/usr/local/lib/python3.5/dist-packages/flask_socketio/__init__.py", line 23, in <module>
    from .namespace import Namespace
  File "/usr/local/lib/python3.5/dist-packages/flask_socketio/namespace.py", line 1, in <module>
    from socketio import Namespace as _Namespace
ImportError: cannot import name 'Namespace'

**Comment by royrusso** [comment]
I *think* the problem is that you have existing libraries in the environment that supersede what is in requirements. I use 3.5.0 to test locally without issues, but I have a dedicated venv for HQ.

Any chance you can set up a venv for this install or use the docker image?

**Comment by Moebius2722** [comment]
I can test venv, but I need some help for set up in 3.5.0 version.

**Comment by royrusso** [comment]
Ok. So maybe the base py env you originally used had more current libraries that caused collisions. Good to know.
