### ISSUE TITLE
Error in installing elasticsearch-HQ

### ISSUE THREAD

**Issue by SenthilkumarRasan** [ElasticHQ/elasticsearch-HQ#410]
### General information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **ElasticHQ Version**: 3.4
- **Elasticsearch Version**: 6.3
- **Python version**: 3.7
- **Browser Vendor and Version (if applicable)**:

### Issue Description

Error in installing elasticmasterHQ. Error stating that Microsoft visual C++ 14.0 required. I have installed VS build tools for VS 2015 (Version 14.0.23026). Still i am getting the same error. There is another error  

python-socketio 2.0.0 has requirement python-engineio>=2.2.0, but you'll have python-engineio 2.0.2 which is incompatible.

![elastichqmaster](https://user-images.githubusercontent.com/34168946/42334436-db93a192-8042-11e8-9ecb-bd365eb77c83.JPG)

**Comment by SenthilkumarRasan** [comment]
Thanks. Issue with python engineio resolved. Still i have issue with Microsoft visula C++ Build tools. I have installed Build tools fro visual studio 2015 (14.0, 23026). Still i am getting same error stating that build tools 14.0 required

**Comment by SenthilkumarRasan** [comment]
Its working after installing visual C++ through visual studio installer. Thanks

**Comment by MaxiMukh** [comment]
I have the same problem while installing ElasticSearchHQ on Ubuntu 16.04 Server.
I installed Python-3.5.1 with PIP and automatic resolve dependencies.
In the installation process I got the error:
`python-socketio 2.0.0 has requirement python-engineio>=2.2.0, but you'll have python-engineio 2.0.2 which is incompatible.`
Please, tell me, how I can resolve this issue?
