### ISSUE TITLE
Minor typographical error: "Indicies"

### ISSUE THREAD

**Issue by abc** [ElasticHQ/elasticsearch-HQ#412]
### General information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Any
- **ElasticHQ Version**: 3.4.0
- **Elasticsearch Version**: 3.6.4
- **Python version**: 3.4
- **Browser Vendor and Version (if applicable)**: Any

### Issue Description

When viewing a cluster, an infobox displays the number of indices that are on the cluster. The label for this is misspelled as 'Indicies'. 

This should be corrected to 'Indices'

**Comment by royrusso** [comment]
Thanks. Looks like I've been spelling it wrong all these years.
