### ISSUE TITLE
EHQ is spewing a LOT of sqlalchemy.engine.base.Engine logs in INFO

### ISSUE THREAD

**Issue by jakubgs** [ElasticHQ/elasticsearch-HQ#418]
### Issue Description
I'm seeing a LOT of logs that start with `sqlalchemy.engine.base.Engine` and are just SQL statements. Why is that?
1. I'm not using the UI constantly, so why am I seeing so many sql statements? I'm seeing ~5k logs per hour like that constantly.
2. Why is this in `INFO` rather than in `DEBUG` log level?

### Source Code / Logs
```
INFO #011 sqlalchemy.engine.base.Engine #011 base._execute_context:1151 #011 SELECT cluster.cluster_name AS cluster_cluster_name, cluster.cluster_ip AS cluster_cluster_ip, cluster.cluster_port AS cluster_cluster_port, cluster.cluster_scheme AS cluster_cluster_scheme, cluster.cluster_version AS cluster_cluster_version, cluster.cluster_username AS cluster_cluster_username, cluster.cluster_password AS cluster_cluster_password
INFO #011 sqlalchemy.engine.base.Engine #011 base._begin_impl:682 #011 BEGIN (implicit)
INFO #011 sqlalchemy.engine.base.Engine #011 base._rollback_impl:702 #011 ROLLBACK
INFO #011 sqlalchemy.engine.base.Engine #011 base._execute_context:1154 #011 ()
INFO #011 sqlalchemy.engine.base.Engine #011 base._begin_impl:682 #011 BEGIN (implicit)
INFO #011 sqlalchemy.engine.base.Engine #011 base._execute_context:1151 #011 SELECT cluster.cluster_name AS cluster_cluster_name, cluster.cluster_ip AS cluster_cluster_ip, cluster.cluster_port AS cluster_cluster_port, cluster.cluster_scheme AS cluster_cluster_scheme, cluster.cluster_version AS cluster_cluster_version, cluster.cluster_username AS cluster_cluster_username, cluster.cluster_password AS cluster_cluster_password
```

**Comment by royrusso** [comment]
You can lower the sqlalchemy loglevel to DEBUG in the logging.json file: http://docs.elastichq.org/installation.html#logging

I don't see why it would be constantly spewing though... the SQLLite DB is hit only when there is a request. Do you have a load balancer pinging up constantly for uptime?

**Comment by jakubgs** [comment]
>You can lower the sqlalchemy loglevel to DEBUG in the logging.json file:
That makes no sense. The messages are `INFO`, if I go lower to `DEBUG` they will still keep showing up. The only thing that makes sense is going __up__ to `WARNING`.

It sits behing a oauth2 proxy, it shouldn't do healthchecks.

**Comment by jakubgs** [comment]
Also, these messages shouldn't be in `INFO` anyway, they should be in `DEBUG`.

**Comment by royrusso** [comment]
I can't control that they are in `INFO`, that's up to SQLAlchemy. You can set it to ERROR in the config, if it bothers you. 

If this is the only query being executed repeatedly, it looks like the one from the homepage, so something must be pinging it.

**Comment by jakubgs** [comment]
>I can't control that they are in INFO, that's up to SQLAlchemy.hh
No, but you can control whether they show up and whether it's as part of your applicaiton logs.

http://docs.sqlalchemy.org/en/latest/core/engines.html#configuring-logging
>By default, the log level is set to logging.WARN within the entire sqlalchemy namespace so that no log operations occur, even within an application that has logging enabled otherwise.

As far as I can tell __you__ set it to `INFO`:
https://github.com/ElasticHQ/elasticsearch-HQ/blob/f427f9f7ffea0bbb9034774964cf6245749f393f/elastichq/config/logger.json#L32-L33

Which is not the default behaviour of SQLAlchemy. Why did you do that?

**Comment by royrusso** [comment]
I will create a ticket, so the `master` branch and releases have more sane and less chatty logging. `develop` can stay verbose. 

In the event of an issue, I'll add a flag to the startup parameters to produce verbose logs that people can post here.
