### ISSUE TITLE
how can install elasticsearch-HQ with offline ?

### ISSUE THREAD

**Issue by zqc0512** [ElasticHQ/elasticsearch-HQ#420]
the machine can't connect to the network .
how can install elasticsearch-HQ with offline  and install with the dependency package ?
which dependency package need install ?

**Comment by royrusso** [comment]
I'm not sure you can... you can possible try the docker install.

**Comment by zqc0512** [comment]
as this   flow  i find offline install but  can't start @royrusso 
https://github.com/ElasticHQ/elasticsearch-HQ/issues/421

**Comment by zqc0512** [comment]
can close as #421
