### ISSUE TITLE
can not access HQ from web

### ISSUE THREAD

**Issue by alantany** [ElasticHQ/elasticsearch-HQ#427]
### General information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Red Hat Enterprise Linux Server release 6.7 
- **ElasticHQ Version**:
3.4.1
- **Elasticsearch Version**:
6.3
- **Python version**: 
3.5.6
- **Browser Vendor and Version (if applicable)**:
ie 8/chrome/firefox
### Issue Description
I have started HQ and have it listenning on 5000 port successfully,but can not access it from web

### Source Code / Logs

Include any logs or source code that would be helpful to diagnose the problem. If including stacktrace, please include the full stacktrace. 

Large logs and files should be attached. Try to provide a reproducible test case or steps that are the bare minimum necessary to generate the problem.

![image](https://user-images.githubusercontent.com/26447990/44338514-aab52e00-a4b0-11e8-9f6c-4087d28807eb.png)

**Comment by alantany** [comment]
i can tenlet IP:5000 ,but can not open the web page.

**Comment by alexwang789** [comment]
I have the same problem, it seems likely happen while offline install and running
Have you solved the problem yet?

**Comment by royrusso** [comment]
There must be something in between you and the flask server if this is hapening. Have you tried reaching it from inside the network?
