### ISSUE TITLE
Include percentage of space used when showing File System Info under "Node Info"

### ISSUE THREAD

**Issue by pushshift** [ElasticHQ/elasticsearch-HQ#433]
For people who use percentage of disk space used to quickly determine ES watermark levels, it would be very helpful to put the percentage of space used / remaining next to the appropriate fields.

For example:

Available Space | 94.3 GB 
Free Space | 95.3 GB (82%)  <--- Shows how much disk space has been used
Total Space | 503.9 GB

Obviously one could compute this with the info already given, but since CPU and JVM measurements already include percentages, it would be great if disk measurements did as well.

Also, you have Available Space and Free Space which to me seem to be the same thing.  Perhaps we could have:

Available Space  | 94.3 GB  (18% Free)
Used Space | 419.9 GB (82% Used)
Total Space | 503.9 GB

(Numbers made up so might not add up correctly)

Thanks so much for all your hard work!

**Comment by sdesse** [comment]
Hello, 
I was thinking the same.
Coming from KOPF I think this could be useful to add to the node view:
- When a node has the master role but is not elected we could show an unchecked box
- Heap info could show heap used/total, something like 50% - 2/4GB
- Disk used could show % like 80% - 80/100GB
- The uptime and elasticsearch/JVM version at the node level (to see mismatches)

**Comment by royrusso** [comment]
I'll add to the next release. @pushshift the only thing I'd change is that available != free.

`available = free - reserved filesystem blocks`

@sdesse I'll add your suggestions on to the same commit.
