### ISSUE TITLE
I use elastcisearch-HQ in a offline, it is too slow

### ISSUE THREAD

**Issue by jffree** [ElasticHQ/elasticsearch-HQ#437]
### General information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **ElasticHQ Version**: latest(docker)
- **Elasticsearch Version**: 6.4.2
- **Python version**:  3.6
- **Browser Vendor and Version (if applicable)**:

### Issue Description

I use elastcisearch-HQ(docker latest version) in a offline, but it try to access some other site. 
Such as cdnjs.cloudflare.com  and fonts.googleapis.com.
I wait HOME page for 160126 ms.

**Comment by royrusso** [comment]
This doesn't sound like "offline". You'll have to give a little more info for us to debug.

**Comment by royrusso** [comment]
I see it now calling out to googleapis and cloudflare.
