### ISSUE TITLE
ModuleNotFoundError: No module named 'flask'

### ISSUE THREAD

**Issue by geekyouth** [ElasticHQ/elasticsearch-HQ#440]
deepin@deepin-PC:/app/elk6.5/elasticsearch-HQ-3.4.1$ python3 application.py
Traceback (most recent call last):
  File "application.py", line 5, in <module>
    from elastichq import create_app
  File "/app/elk6.5/elasticsearch-HQ-3.4.1/elastichq/__init__.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

**Comment by royrusso** [comment]
Looks like you didn't install the requirements.

**Comment by tanmarpaul** [comment]
If you use python3 to start HQ you might also need to install the requirements with pip3 instead of pip.

_(I know it's closed but this would have helped me more than "install the requirements")_

**Comment by royrusso** [comment]
> If you use python3 to start HQ you might also need to install the requirements with pip3 instead of pip.
> 
> _(I know it's closed but this would have helped me more than "install the requirements")_

That's fair. I've hesitated writing up a lengthy install doc, as the 2M downloads of the Docker image tells me more people are just opting for that and not dealing with all the wrangling of requirements and fighting different py versions.
