### ISSUE TITLE
Support Kubernetes deployment

### ISSUE THREAD

**Issue by abessifi** [ElasticHQ/elasticsearch-HQ#442]
### New feature request:

By default the built Docker image is not compatible with Kubernetes and OpenShift platforms and needs to be run with a privileged user (root in this case which is not allowed by default on Kubernetes).

The Dockerfile needs to be modified so the built images can be ran on Kubernetes and still supported by Docker natively.

**Comment by royrusso** [comment]
@abessifi Is there anything that you believe should be mentioned in the docs that users should do differently with this change?

**Comment by abessifi** [comment]
Thanks @royrusso for merging the #443 PR.
In fact nothing special to mention in the docs. The new Dockerfile still work correctly with Docker. I've just refactored it in a way that the built Docker image is Kubernetes/OpenShift compatible by default.
