### ISSUE TITLE
Cannot connect with username/password when the password starts with a digit

### ISSUE THREAD

**Issue by kalumkalac** [ElasticHQ/elasticsearch-HQ#454]
### General information

- **Any**:
- **ElasticHQ Version**: 3.5.0
- **Elasticsearch Version**: 6.5.3
- **Python version**: 3.4

### Issue Description

When I connect with a username/password, if the password starts with a digit, ElasticHQ considers it as the port of the elasticsearch cluster. See in the console of the browser.

### Source Code / Logs

For example, the URL: `https://test:1test@localhost:9200`

ElasticHQ tries to connect to: 

```
ip: "localhost", port: "1", username: "test", password: "1test", use_ssl: false}
```

As you can see, the port is wrong.

**Comment by pcasa** [comment]
Fix pushed to develop branch.  Should be merged to master shortly.

**Comment by anitakrueger** [comment]
@pcasa @royrusso I just ran into this issue and was wondering why elasticsearch-HQ would try to connect to port 53.
Any chance this fix can be merged into develop please?

**Comment by royrusso** [comment]
Is this not merged in to develop yet? Seems that @pcasa did.

**Comment by anitakrueger** [comment]
Ah ok. I'm using the latest docker image and it's not in there unfortunately.

**Comment by royrusso** [comment]
There should be a docker image for the develop branch.

**Comment by francisdb** [comment]
Fixed half a year ago but still not fixed in the latest docker image?

**Comment by royrusso** [comment]
Should be on the develop docker image. I will hopefully do a release this week. :-)

**Comment by royrusso** [comment]
Should be in master. If still broken, please reopen this or create a new ticket.

**Comment by francisdb** [comment]
Thank you! I can confirm this to be fixed.
