### ISSUE TITLE
CPU usage not displayed

### ISSUE THREAD

**Issue by Starwalker2000** [ElasticHQ/elasticsearch-HQ#456]
### General information

- **ElasticHQ Version**: 3.5.0/3.4.1
- **Elasticsearch Version**: 6.2.2
- **Python version**: 3.5.6

### Issue Description

The _nodes/stats API of ES 6.2.2 returns CPU percent and load_average like following:

> {
>     "nodes":
>     {
>         "xxx":
>         {
>             "os":
>             {
>                 "cpu":
>                 {
>                     "percent": 64,
>                     "load_average":
>                     {
>                         "1m": 7.25,
>                         "5m": 6.62,
>                         "15m": 6.46
>                     }
>                 }
>             }
>         }
>     }
> }

But in `Task.py`, `os.load_average` and `os.cpu_percent` are used to get the two metrics. Should be `os.cpu.percent` and `os.cpu.load_average.XXX`.

### Source Code / Logs

Now:
> "os_load_average": jmespath.search("os.load_average", node_dict),
> "os_cpu_percent": jmespath.search("os.cpu_percent", node_dict),

One possible solution:
> "os_load_average": jmespath.search("os.load_average", node_dict) if jmespath.search("os.load_average", node_dict) is not None else jmespath.search("os.cpu.load_average.\"1m\"", node_dict),
> "os_cpu_percent": jmespath.search("os.cpu_percent", node_dict) if jmespath.search("os.cpu_percent", node_dict) is not None else jmespath.search("os.cpu.percent", node_dict),

**Comment by royrusso** [comment]
I would not doubt the geniuses at Elastic making backward incompatible changes. I'll have a look and fix for next release.

**Comment by STamil** [comment]
Hi,
 I am also facing this issue could you please fixed the same.
