### ISSUE TITLE
Installing elasticHQ without network connection to the web

### ISSUE THREAD

**Issue by DRhyme** [ElasticHQ/elasticsearch-HQ#457]
### General information

- **CentOS Linux release 7.6.1810**:
- **ElasticHQ Version (latest)**:
- **Elasticsearch 6.5.1**:
- **Python 3.6.6**: 
- **Chrome Version 71.0.3578.98**:

### Issue Description

I tried to install elasticsearch-HQ at work within my development Environment.  After running Step 2 pip install -r requirements.txt i got into a lopp with the result, presented in the Log secton below.

Are there any dependencies i need to consider while installing elasticHQ in a local network that is not connected with the web?

Thank you. 

### Source Code / Logs

Collecting jmespath==0.9.3 (from -r requirements.txt (line 1))
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6f218e0510>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/jmespath/

**Comment by royrusso** [comment]
Your best bet would be to use the docker container. If you're trying to build from source, then you do need an active connection to pypi at the least.
