### ISSUE TITLE
Two clusters with same name gives conflicting data on the dashboard

### ISSUE THREAD

**Issue by sarmak1179** [ElasticHQ/elasticsearch-HQ#458]
### General information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **ElasticHQ Version**: latest (3.5.0)
- **Elasticsearch Version**: 6.5.x
- **Python version**:  2.7.12

### Issue Description

I have two ES clusters on different nodes with the same name.
I added the first cluster using the settings (automatically added when I first accessed elastichq)
From Settings, I tried to add the second cluster by giving the ES URL. This ES cluster also has the same name elasticsearch.
The message appears that the cluster is added successfully., though no second entry is added here on the UI.

Now when I go to the dashboard, it shows the indices details on the first cluster that is added. But the node frame and indices frames are updated to 2nd cluster.

Is this expected if I have the same cluster name?

**Comment by alisanguo** [comment]
I have the same problem

**Comment by royrusso** [comment]
There are no plans to address this at the moment. There is no other way (that I have found) to uniquely identify a cluster except name. IP addresses can change, so that's not reliable either.
