### ISSUE TITLE
[Contrib] - ElasticHQ on OpenShift

### ISSUE THREAD

**Issue by ricardozanini** [ElasticHQ/elasticsearch-HQ#463]
Hi!

I just would like to share that I've managed to install ElasticHQ on OpenShift cluster successfully to monitor the internal logging indices. Could be a little tricky because the ES on OpenShift requires certificate keys to access the internal monitoring API. 

I've managed to get it work by adding a NGINX proxy in front of the ES service. This way, the ElasticHQ container could easily connect to it.

The how-to and the artifacts produced for this to work could be found at:
https://github.com/ricardozanini/elastic-hq-openshift

If the community agrees, I can send a PR to add this to the README.md. 

Another idea that could work is adding client certificate authentication to the [ConnectionService.py](elasticsearch-HQ/blob/master/elastichq/service/ConnectionService.py) class.

Best wishes,

**Comment by royrusso** [comment]
Hi Ricardo, 

Thank you. This is helpful, and I will add this to the docs. I'm curious if you have the websocket screens (metrics) working. This is a problem people seem to experience fronting with nginx.

**Comment by ricardozanini** [comment]
Hi Roy!

Yup, websockets are working as intended! :)

Do you mind merging a PR with the assets of my repo? So I could archive mine, adding the OpenShift templates directly into the ElasticHQ sources.

**Comment by royrusso** [comment]
Yes. Just give me time to review it, but that makes sense. You have some documentation there that is also helpful, so it may be good to merge that in as well, under one folder.

**Comment by ricardozanini** [comment]
While working in the PR, I wrote a little article to give more background info to deploying ElasticHQ on OpenShift: https://medium.com/@ricardozanini/how-to-monitor-openshift-elasticsearch-logging-with-elastichq-fe641a6b04e3

As soon as we merge the PR, I'll edit the article to refer to this repo. :)

**Comment by ricardozanini** [comment]
@royrusso do you mind taking a look at the feature before I open the PR?

https://github.com/ricardozanini/elasticsearch-HQ/tree/feature/openshift_deploy

Added a little section on the main README.md and the `openshift` directory with all the assets into it.

thanks!

**Comment by royrusso** [comment]
Looks good, at least from my read-thru. I really appreciate the help. I have many open tickets on getting metrics working with nginx, and this may have, in an unintended way, solved them. I need to test that.

**Comment by ricardozanini** [comment]
@royrusso if you want to see the metrics working, I uploaded a screenshot on the Medium article: https://cdn-images-1.medium.com/max/1600/1*ezZV-MN3BtpPeSriF7OZFw.png

**Comment by royrusso** [comment]
Yep. I read the article and saw it there.

**Comment by royrusso** [comment]
Merged. I may take pieces of it and add to the online docs. Specially if the NGINX config solves the issue people are having with websockets + metrics.
