### ISSUE TITLE
support disable ssl verification

### ISSUE THREAD

**Issue by strbak** [ElasticHQ/elasticsearch-HQ#480]
### General information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): ubuntu 16.04
ElasticHQ Version: 3.50
Elasticsearch Version: 6.6.2
Python version: 3.6
Browser Vendor and Version (if applicable):
### Issue Description

with es 6.8.1 and above , auth & ssl is common , many es clusters are built are with passwd ,please kinldy help consider the problems

### Source Code / Logs
do_handshake self._sslobj.do_handshake() ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

**Comment by cboothe** [comment]
This would be great! The Open Distro For Elasticsearch is setup out of the box with a generic SSL configuration, using the --insecure option to connect.

**Comment by abh** [comment]
I have it setup with a CA mounted in the container, but it still doesn't work. Maybe the python stuff isn't supporting ECDSA certificates?  In any case I'd be happy to just disable verification in this environment.  ElasticHQ is talking on the private k8s network to ES in the same namespace with limited network access to anything else.

**Comment by royrusso** [comment]
Closing. Related to #471
