### ISSUE TITLE
Release 3.5.1 installed, but main page shows 3.5.0 installed

### ISSUE THREAD

**Issue by pommetjehorlepiep** [ElasticHQ/elasticsearch-HQ#491]
### General information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Alpine 3.10
- **ElasticHQ Version**: 3.5.1
- **Elasticsearch Version**:  N/A
- **Python version (ignore is using docker image)**: 3.7.3
- **Browser Vendor and Version (if applicable)**:

### Issue Description

Installed release 3.5.1 using source file (tar.gz). On the main page, it shows the installed version
incorrectly as being **3.5.0**

### Source Code / Logs
N/A

![Screenshot](https://user-images.githubusercontent.com/8982487/65603765-9c0d4480-dfe9-11e9-8b49-070c827e683d.png)

**Comment by royrusso** [comment]
I'm not able to reproduce it. Downloading the zip from master branch outputs the correct version. Is it maybe the browser cache?

**Comment by pommetjehorlepiep** [comment]
Hi Roy, it is/was not the browser cache...

Installed the freshly released 3.5.2 version, and that one is showing the correct version! :)

Did some comparisons between 3.5.2 and 3.5.1 and found that the **API_VERSION** in 3.5.1 is set to **3.5.0**. In 3.5.2 it's set correctly to **3.5.2**

Compare https://github.com/ElasticHQ/elasticsearch-HQ/blob/v3.5.1/elastichq/config/settings.py vs 
https://github.com/ElasticHQ/elasticsearch-HQ/blob/v3.5.2/elastichq/config/settings.py

So problem is solved in latest version. Probably no need to fix 3.5.1 for this.

**Comment by royrusso** [comment]
Yes. I after releasing 3.5.2, I realized, I somehow, still unknown, messed up the tagging. Thanks!
