### ISSUE TITLE
Download version elastichq 3.5.3

### ISSUE THREAD

**Issue by robsonads** [ElasticHQ/elasticsearch-HQ#495]
Where can I download version 3.5.3 Elastichq?
My system operation is CentOS 7.

I have a day job. ;-)

**Comment by royrusso** [comment]
Tagged now as v3.5.3. 3.5.4 should be out soon though... tagged appropriately. 

Congrats on the day job! :-)

**Comment by robsonads** [comment]
Is there a way to put a screen for users to enter their login and password?
